/* ==========================================================================
   Soft Skill Zone — Interview & Viva sawaalon ka bank
   --------------------------------------------------------------------------
   480 sawaal, topic ke hisaab se. Har entry:
     t = topic, q = sawaal, a = jawab (chhota, bolne layak)

   Jawab jaanbujh kar 1-2 line ke rakhe hain. Interview me lamba bhashan nahi
   chalta — seedha, saaf jawab chahiye. Student ise padh kar BOL kar practice
   kare, yahi is tool ka maqsad hai.
   ========================================================================== */

export const QA_TOPICS = [
  "Computer Basics",
  "Windows 11",
  "MS Word",
  "MS Excel",
  "PowerPoint",
  "Internet & Email",
  "Tally & Accounts",
  "GST & Tax",
  "Interview / HR"
];

export const INTERVIEW_QA = [
  /* ---------------- Computer Basics (55) ---------------- */
  { t: "Computer Basics", q: "Computer kya hai?", a: "Ek electronic machine jo data leta hai, use process karta hai aur result deta hai. Ye khud nahi sochta — jo aap bataate hain wahi karta hai." },
  { t: "Computer Basics", q: "Hardware aur Software me kya farq hai?", a: "Hardware wo hai jise chhoo sakte hain — keyboard, mouse, CPU. Software wo hai jo dikhta hai par chhoo nahi sakte — Windows, MS Word." },
  { t: "Computer Basics", q: "CPU ko computer ka dimaag kyun kehte hain?", a: "Kyunki saara calculation aur faisla wahi karta hai. Baaki parts sirf data dete-lete hain." },
  { t: "Computer Basics", q: "RAM kya hai?", a: "Temporary memory. Jo kaam abhi chal raha hai wo RAM me rehta hai. Bijli jaate hi khali ho jaati hai." },
  { t: "Computer Basics", q: "RAM aur ROM me farq?", a: "RAM temporary hai aur likhi-mitai ja sakti hai. ROM permanent hai, usme computer ke chalu hone ke nirdesh rehte hain." },
  { t: "Computer Basics", q: "Hard Disk kya karti hai?", a: "Aapka data permanently rakhti hai — files, photos, software. Bijli jaane par bhi data rehta hai." },
  { t: "Computer Basics", q: "HDD aur SSD me kaunsa behtar hai?", a: "SSD — usme koi ghoomne wala part nahi hota, isliye 5-10 guna tez chalti hai aur girne par kharab nahi hoti." },
  { t: "Computer Basics", q: "Input device ke 4 udaharan dijiye.", a: "Keyboard, Mouse, Scanner, Microphone. Ye computer ko data dete hain." },
  { t: "Computer Basics", q: "Output device ke 4 udaharan dijiye.", a: "Monitor, Printer, Speaker, Projector. Ye computer se result bahar laate hain." },
  { t: "Computer Basics", q: "Kaunsa device input aur output dono hai?", a: "Touch screen, aur modem bhi. Pen drive ko bhi dono mana jaata hai." },
  { t: "Computer Basics", q: "1 KB me kitne Byte hote hain?", a: "1024 Byte. Aage: 1024 KB = 1 MB, 1024 MB = 1 GB, 1024 GB = 1 TB." },
  { t: "Computer Basics", q: "1 Byte me kitne Bit hote hain?", a: "8 bit. Ek bit sirf 0 ya 1 ho sakta hai." },
  { t: "Computer Basics", q: "Bit aur Byte me farq?", a: "Bit sabse chhoti ikai hai (0 ya 1). 8 bit milkar 1 byte banate hain, jo ek akshar rakh sakta hai." },
  { t: "Computer Basics", q: "Operating System kya hai?", a: "Wo software jo hardware aur user ke beech kaam karta hai. Jaise Windows, Linux, Android." },
  { t: "Computer Basics", q: "System software aur Application software me farq?", a: "System software computer ko chalata hai (Windows). Application software aapka kaam karta hai (MS Word, Tally)." },
  { t: "Computer Basics", q: "Booting kya hoti hai?", a: "Computer on karne par Operating System ka memory me load hona. Cold boot = band se chalu, Warm boot = restart." },
  { t: "Computer Basics", q: "BIOS kya hai?", a: "Motherboard par lagi ek chhoti chip ka program jo computer on hote hi hardware check karke OS ko chalu karta hai." },
  { t: "Computer Basics", q: "Motherboard kya karta hai?", a: "Ye woh main board hai jispar CPU, RAM aur baaki saare parts jude hote hain — sabko aapas me jodta hai." },
  { t: "Computer Basics", q: "SMPS ka kaam kya hai?", a: "Bijli ke AC current ko DC me badal kar computer ke parts ko sahi voltage deta hai." },
  { t: "Computer Basics", q: "UPS kyun lagate hain?", a: "Bijli jaane par kuch minute ka backup deta hai, taaki kaam save karke computer theek se band kar sakein." },
  { t: "Computer Basics", q: "File aur Folder me farq?", a: "File me asli data hota hai. Folder ek dabba hai jisme kai files rakhi jaati hain." },
  { t: "Computer Basics", q: "File extension kya batata hai?", a: "File kis type ki hai. .docx = Word, .xlsx = Excel, .pdf = PDF, .jpg = photo." },
  { t: "Computer Basics", q: "Virus kya hai?", a: "Ek nuksaan pahunchane wala program jo khud ko copy karke files kharab karta hai ya data churata hai." },
  { t: "Computer Basics", q: "Antivirus kya karta hai?", a: "Virus ko dhundhta hai, rokta hai aur hata deta hai. Use regular update karna zaroori hai." },
  { t: "Computer Basics", q: "Computer slow ho to sabse pehle kya check karenge?", a: "Startup me kitne program chalu hain, C drive me jagah bachi hai ya nahi, aur RAM kitni bhari hai — Task Manager se." },
  { t: "Computer Basics", q: "Formatting kya hoti hai?", a: "Drive ka poora data mitakar use dobara naya jaisa banana. Karne se pehle backup zaroori hai." },
  { t: "Computer Basics", q: "Backup kyun zaroori hai?", a: "Hard disk kabhi bhi kharab ho sakti hai. Backup na ho to saara kaam ek pal me chala jaata hai." },
  { t: "Computer Basics", q: "Printer ke do prakar bataiye.", a: "Inkjet — ink se, photo achhi aati hai. Laser — toner se, tez aur saste me zyada page." },
  { t: "Computer Basics", q: "Scanner kya karta hai?", a: "Kagaz ke document ko photo ki tarah computer me le aata hai." },
  { t: "Computer Basics", q: "OCR kya hai?", a: "Optical Character Recognition — scan ki hui photo me se text pehchaan kar use edit karne layak bana deta hai." },
  { t: "Computer Basics", q: "Software ka license kya hota hai?", a: "Company ki wo ijaazat jiske tehat aap software istemaal kar sakte hain. Bina license ka software galat aur asurakshit hai." },
  { t: "Computer Basics", q: "Open source software kya hai?", a: "Jiska code sabke liye khula hai aur aksar muft hota hai — jaise LibreOffice, Linux." },
  { t: "Computer Basics", q: "GUI kya hai?", a: "Graphical User Interface — icon, button aur mouse se computer chalana. Iske pehle sirf command likhni padti thi." },
  { t: "Computer Basics", q: "Shortcut key ka faayda?", a: "Kaam bahut tez ho jaata hai. Mouse tak haath le jaane me jo time jaata hai wo bach jaata hai." },
  { t: "Computer Basics", q: "Data aur Information me farq?", a: "Data kacchi cheez hai — jaise marks ki list. Use process karke jo matlab nikalta hai (result, percentage) wo Information hai." },
  { t: "Computer Basics", q: "Database kya hai?", a: "Data ko table ki shakal me tarteeb se rakhne ka tareeka, taaki dhundhna aur nikalna aasan ho." },
  { t: "Computer Basics", q: "Cache memory kya hai?", a: "CPU ke bilkul paas ki bahut tez memory, jisme baar-baar kaam aane wala data rakha jaata hai." },
  { t: "Computer Basics", q: "Motherboard par CMOS battery kyun hoti hai?", a: "Computer band hone par bhi date, time aur BIOS settings yaad rakhne ke liye." },
  { t: "Computer Basics", q: "Port kya hota hai?", a: "Wo jagah jahan bahari device jodte hain — USB, HDMI, LAN port." },
  { t: "Computer Basics", q: "USB ka poora naam?", a: "Universal Serial Bus. Isse pen drive, mouse, printer sab jud sakte hain." },
  { t: "Computer Basics", q: "Resolution kya batata hai?", a: "Screen par kitne pixel hain. Jitne zyada, tasveer utni saaf. Jaise 1920x1080 (Full HD)." },
  { t: "Computer Basics", q: "Refresh rate kya hai?", a: "Screen ek second me kitni baar tasveer badalti hai — 60Hz matlab 60 baar." },
  { t: "Computer Basics", q: "Computer ki 5 generation me sabse pehli kis par thi?", a: "Vacuum tube par. Fir transistor, IC, microprocessor, aur ab AI par." },
  { t: "Computer Basics", q: "Supercomputer kis kaam aata hai?", a: "Mausam ka anuman, space research, aur bahut bade calculation ke liye. India ka PARAM iska udaharan hai." },
  { t: "Computer Basics", q: "Server kya hota hai?", a: "Ek badi computer jo doosre computers ko data ya service deti hai — jaise website ka server." },
  { t: "Computer Basics", q: "Client-Server ka matlab?", a: "Client maangta hai (aapka browser), server deta hai (website ka computer)." },
  { t: "Computer Basics", q: "Cloud storage kya hai?", a: "Internet par kisi company ke server par aapka data — Google Drive, OneDrive. Kahin se bhi khol sakte hain." },
  { t: "Computer Basics", q: "Compression kya karti hai?", a: "File ka size chhota kar deti hai taaki jagah kam lage aur bhejne me aasani ho — jaise ZIP." },
  { t: "Computer Basics", q: "Shut down aur Sleep me farq?", a: "Shut down me computer poora band hota hai. Sleep me kaam waisa hi rukka rehta hai aur turant wapas aa jaata hai." },
  { t: "Computer Basics", q: "Safe Mode kab istemaal karte hain?", a: "Jab computer theek se chalu na ho. Isme sirf zaroori driver load hote hain, taaki dikkat dhundh sakein." },
  { t: "Computer Basics", q: "Driver kya hota hai?", a: "Wo chhota software jo hardware ko Windows se baat karna sikhata hai — printer driver ke bina printer nahi chalega." },
  { t: "Computer Basics", q: "Task Manager kis kaam aata hai?", a: "Kaun se program chal rahe hain aur kitni RAM/CPU le rahe hain, ye dekhne aur atke program ko band karne ke liye. Ctrl+Shift+Esc." },
  { t: "Computer Basics", q: "Recycle Bin kya hai?", a: "Delete ki hui files ka asthai dabba. Wahan se wapas laayi ja sakti hain, jab tak khali na kar dein." },
  { t: "Computer Basics", q: "Shift+Delete kya karta hai?", a: "File ko Recycle Bin me bheje bina seedhe hamesha ke liye mita deta hai. Isliye dhyan se use karein." },
  { t: "Computer Basics", q: "Ek achhe computer operator me kya khoobi honi chahiye?", a: "Tez aur sahi typing, MS Office ki achhi jaankari, data me safai aur dhyan, aur backup ki aadat." },

  /* ---------------- Windows 11 (45) ---------------- */
  { t: "Windows 11", q: "Windows 11 me Start button kahan hota hai?", a: "Taskbar ke beech me — Windows 10 tak ye baayein kone me tha. Chaahein to settings se wapas baayein la sakte hain." },
  { t: "Windows 11", q: "File Explorer kholne ka shortcut?", a: "Windows + E" },
  { t: "Windows 11", q: "Desktop dikhane ka shortcut?", a: "Windows + D — dobara dabane par khidkiyan wapas aa jaati hain." },
  { t: "Windows 11", q: "Settings kholne ka shortcut?", a: "Windows + I" },
  { t: "Windows 11", q: "Screenshot lene ka sabse achha tareeka?", a: "Windows + Shift + S — Snipping Tool khulta hai aur aap chuni hui jagah ka screenshot le sakte hain." },
  { t: "Windows 11", q: "Snap Layouts kya hai?", a: "Windows 11 ka feature — maximize button par mouse rakhne par screen bantne ke design dikhte hain, jisse do-teen app saath dekh sakte hain." },
  { t: "Windows 11", q: "Virtual Desktop kis kaam aata hai?", a: "Alag-alag kaam ke liye alag desktop — ek me office ka kaam, ek me padhai. Windows + Tab se." },
  { t: "Windows 11", q: "Task View ka shortcut?", a: "Windows + Tab" },
  { t: "Windows 11", q: "Do khuli khidkiyon ke beech badalne ka shortcut?", a: "Alt + Tab — dabaye rakhein to saari khidkiyan dikhti hain." },
  { t: "Windows 11", q: "Khidki ko aadhi screen par lagane ka shortcut?", a: "Windows + baayan/dayan arrow" },
  { t: "Windows 11", q: "Computer lock karne ka shortcut?", a: "Windows + L — seat chhodte waqt hamesha lagayein." },
  { t: "Windows 11", q: "Run box kholne ka shortcut?", a: "Windows + R" },
  { t: "Windows 11", q: "Control Panel kholne ki command?", a: "Run me 'control' likhkar Enter." },
  { t: "Windows 11", q: "Windows me kisi cheez ko dhundhne ka shortcut?", a: "Windows + S (ya sirf Windows dabakar type karna)." },
  { t: "Windows 11", q: "Naya folder banane ka shortcut?", a: "Ctrl + Shift + N" },
  { t: "Windows 11", q: "File ka naam badalne ki key?", a: "F2" },
  { t: "Windows 11", q: "File ki properties dekhne ka shortcut?", a: "Alt + Enter" },
  { t: "Windows 11", q: "Hidden files kaise dikhayein?", a: "File Explorer me View → Show → Hidden items par tick lagayein." },
  { t: "Windows 11", q: "File extension kaise dikhayein?", a: "View → Show → File name extensions par tick. Ye virus pehchanne me madad karta hai." },
  { t: "Windows 11", q: "Disk Cleanup kya karta hai?", a: "Temporary files, purani update aur Recycle Bin ka kachra hata kar jagah khali karta hai." },
  { t: "Windows 11", q: "Defragment kis drive par nahi karna chahiye?", a: "SSD par. Uske liye Windows khud TRIM chalata hai, defrag se sirf ghisawat badhti hai." },
  { t: "Windows 11", q: "Windows Update kyun zaroori hai?", a: "Naye security ke sudhaar aate hain. Bina update ke computer virus ke liye khula rehta hai." },
  { t: "Windows 11", q: "Windows Defender kya hai?", a: "Windows ke saath aane wala muft antivirus. Aam istemaal ke liye ye kaafi hai." },
  { t: "Windows 11", q: "Firewall ka kaam?", a: "Internet se aane-jaane wale traffic par nazar rakhta hai aur bina ijaazat wale connection rokta hai." },
  { t: "Windows 11", q: "User Account Control (UAC) kya hai?", a: "Wo pop-up jo poochhta hai 'is app ko badlav karne dein?'. Ye bina jaankari software install hone se bachata hai." },
  { t: "Windows 11", q: "Administrator aur Standard user me farq?", a: "Administrator software install kar sakta hai aur settings badal sakta hai. Standard user sirf kaam kar sakta hai — dukaan ke computer par yahi sahi rehta hai." },
  { t: "Windows 11", q: "Computer ka naam kaise badlein?", a: "Settings → System → About → Rename this PC." },
  { t: "Windows 11", q: "Default browser kaise badlein?", a: "Settings → Apps → Default apps → browser chunkar set karein." },
  { t: "Windows 11", q: "Printer kaise add karte hain?", a: "Settings → Bluetooth & devices → Printers & scanners → Add device." },
  { t: "Windows 11", q: "Ek program computer ke saath chalu ho, iske liye?", a: "Task Manager → Startup apps me use Enable kar dein." },
  { t: "Windows 11", q: "Atke hue program ko kaise band karein?", a: "Ctrl + Shift + Esc se Task Manager kholein, program chunkar End task." },
  { t: "Windows 11", q: "Clipboard History kya hai?", a: "Windows + V — pichhli kai copy ki hui cheezein dikhti hain, kisi ko bhi dobara paste kar sakte hain." },
  { t: "Windows 11", q: "Emoji panel ka shortcut?", a: "Windows + . (full stop)" },
  { t: "Windows 11", q: "Zoom in/out kaise karein?", a: "Ctrl ke saath mouse ka wheel ghumayein, ya Ctrl + plus / Ctrl + minus." },
  { t: "Windows 11", q: "System Restore kya karta hai?", a: "Computer ki settings ko pehle ki theek haalat me le jaata hai, bina aapki files mitaye." },
  { t: "Windows 11", q: "Windows me file dhundhne ka aasan tareeka?", a: "File Explorer kholkar upar dayein search box me naam likhein, ya Windows + S." },
  { t: "Windows 11", q: "Drive ka naam kaise badlein?", a: "This PC me drive par right click → Rename." },
  { t: "Windows 11", q: "Ek file ko do jagah rakhna ho to?", a: "Copy karke doosri jagah paste karein (Ctrl+C, Ctrl+V). Move karna ho to Ctrl+X, Ctrl+V." },
  { t: "Windows 11", q: "Bahut si files ek saath kaise chunein?", a: "Ctrl dabakar ek-ek par click karein, ya pehli par click karke Shift dabakar aakhri par click karein." },
  { t: "Windows 11", q: "ZIP file kaise banate hain?", a: "Files chunkar right click → Compress to ZIP file." },
  { t: "Windows 11", q: "Pen drive nikalne se pehle kya karna chahiye?", a: "Taskbar se 'Safely Remove Hardware' par click karein — warna data kharab ho sakta hai." },
  { t: "Windows 11", q: "Windows me date-time galat ho to?", a: "Settings → Time & language → Date & time me 'Set time automatically' on karein. CMOS battery kharab ho to wo badalni padegi." },
  { t: "Windows 11", q: "Blue screen (BSOD) kyun aati hai?", a: "Zyadatar kharab driver, RAM ki dikkat ya hardware fail hone se. Screen par likha error code se wajah pata chalti hai." },
  { t: "Windows 11", q: "Windows ka version kaise dekhein?", a: "Run me 'winver' likhkar Enter." },
  { t: "Windows 11", q: "Ek din ka kaam khatam karke computer band karne ka sahi tareeka?", a: "Pehle saare kaam save karein, program band karein, fir Start → Power → Shut down. Seedha switch band karna nuksaan karta hai." },

  /* ---------------- MS Word (60) ---------------- */
  { t: "MS Word", q: "MS Word kis kaam aata hai?", a: "Letter, application, report, resume — koi bhi likhne wala document banane aur uski sajawat karne ke liye." },
  { t: "MS Word", q: "Word ki file ka extension kya hai?", a: ".docx (naye version me). Purane version me .doc tha." },
  { t: "MS Word", q: "Ribbon kya hai?", a: "Word ke upar ki wo patti jisme Home, Insert, Layout jaise tab hote hain aur unme saare button." },
  { t: "MS Word", q: "Quick Access Toolbar kya hai?", a: "Sabse upar ki chhoti patti jahan Save, Undo jaise roz kaam aane wale button rakh sakte hain." },
  { t: "MS Word", q: "Save aur Save As me farq?", a: "Save purani file par hi likh deta hai. Save As nayi jagah ya naye naam se nayi copy banata hai." },
  { t: "MS Word", q: "Word me naya document kholne ka shortcut?", a: "Ctrl + N" },
  { t: "MS Word", q: "Print preview ka shortcut?", a: "Ctrl + P — wahin preview aur print dono milte hain." },
  { t: "MS Word", q: "Find aur Replace ka shortcut?", a: "Find = Ctrl + F, Replace = Ctrl + H" },
  { t: "MS Word", q: "Replace All kab kaam aata hai?", a: "Jab poore document me ek shabd ko doosre se badalna ho — jaise galat naam 30 jagah likha ho." },
  { t: "MS Word", q: "Text ko beech me laane ka shortcut?", a: "Ctrl + E (Center). Left = Ctrl+L, Right = Ctrl+R, Justify = Ctrl+J" },
  { t: "MS Word", q: "Justify alignment kya karta hai?", a: "Text ko dono taraf se barabar kar deta hai — akhbaar jaisa saaf look aata hai." },
  { t: "MS Word", q: "Line spacing kaise badalte hain?", a: "Home tab → Line and Paragraph Spacing button. Ya Ctrl+1 (single), Ctrl+2 (double), Ctrl+5 (1.5)." },
  { t: "MS Word", q: "Bullets aur Numbering me farq?", a: "Bullets me nishaan (•) lagta hai jab kram zaroori na ho. Numbering me 1,2,3 lagta hai jab kram maayne rakhta ho." },
  { t: "MS Word", q: "Header aur Footer kya hote hain?", a: "Header har page ke upar chhapne wala hissa, Footer neeche ka. Insert tab se lagate hain." },
  { t: "MS Word", q: "Page number kaise daalte hain?", a: "Insert → Page Number → jagah chunein. Ye har page par apne aap badalta rehta hai." },
  { t: "MS Word", q: "Page break kya hai?", a: "Ek jagah se agla content zabardasti naye page se shuru karna. Shortcut Ctrl + Enter." },
  { t: "MS Word", q: "Section break kis kaam aata hai?", a: "Jab document ke alag hisson me alag layout chahiye — jaise ek hissa portrait, doosra landscape." },
  { t: "MS Word", q: "Portrait aur Landscape me farq?", a: "Portrait khada page (lamba), Landscape leta hua page (chauda). Layout → Orientation se badalta hai." },
  { t: "MS Word", q: "Margin kya hoti hai?", a: "Page ke charon taraf chhodi gayi khali jagah. Layout → Margins se ghata-badha sakte hain." },
  { t: "MS Word", q: "Mail Merge kya hai?", a: "Ek hi letter ko 100 alag naam-pate ke saath apne aap banane ka tareeka. Ek Word letter + ek Excel list se." },
  { t: "MS Word", q: "Mail Merge ke steps bataiye.", a: "Mailings → Start Mail Merge → Select Recipients (Excel list) → Insert Merge Field → Preview → Finish & Merge." },
  { t: "MS Word", q: "Mail Merge kahan istemaal hota hai?", a: "Certificate, salary slip, shaadi ka card, admission letter — jahan ek hi format me kai logon ke naam chahiye." },
  { t: "MS Word", q: "Table kaise banate hain?", a: "Insert → Table → kitni row-column chahiye wo chunein." },
  { t: "MS Word", q: "Table me nayi row kaise jodein?", a: "Aakhri cell me Tab dabane par nayi row apne aap ban jaati hai. Ya right click → Insert." },
  { t: "MS Word", q: "Merge Cells kya karta hai?", a: "Do ya zyada cell ko jodkar ek bada cell bana deta hai — heading ke liye kaam aata hai." },
  { t: "MS Word", q: "Word me picture kaise daalein?", a: "Insert → Pictures → This Device se apne computer ki photo chunein." },
  { t: "MS Word", q: "Text Wrapping kya hai?", a: "Photo ke aas-paas text kaise ghumega — Square, Tight, Behind Text. Photo par click karke layout icon se." },
  { t: "MS Word", q: "WordArt kya hai?", a: "Text ko sajawati roop dene ka tareeka — banner aur heading ke liye." },
  { t: "MS Word", q: "SmartArt kis kaam aata hai?", a: "Chart, cycle aur hierarchy jaise diagram banane ke liye — jaise company ka organisation chart." },
  { t: "MS Word", q: "Watermark kaise lagate hain?", a: "Design → Watermark → Custom. 'DRAFT' ya 'COPY' likhna ho to yahi." },
  { t: "MS Word", q: "Style kya hoti hai?", a: "Heading aur text ki tayyar sajawat. Style lagane se poore document me ek jaisa look aata hai aur badalna aasan hota hai." },
  { t: "MS Word", q: "Table of Contents apne aap kaise bane?", a: "Pehle headings par Heading 1/2 style lagayein, fir References → Table of Contents." },
  { t: "MS Word", q: "Spelling check ki key?", a: "F7" },
  { t: "MS Word", q: "Word Count kahan dikhta hai?", a: "Sabse neeche status bar me, ya Review → Word Count." },
  { t: "MS Word", q: "Track Changes kya karta hai?", a: "Aapke har badlav ko rang me dikhata hai, taaki doosra insaan dekh kar accept ya reject kar sake." },
  { t: "MS Word", q: "Comment kis kaam aata hai?", a: "Document me kisi hisse par note lagane ke liye, bina text badle — team ke kaam me bahut upyogi." },
  { t: "MS Word", q: "Word file ko PDF kaise banayein?", a: "File → Save As → type me PDF chunein. Ya File → Export → Create PDF." },
  { t: "MS Word", q: "PDF kyun banate hain?", a: "PDF har computer par bilkul waisa hi dikhta hai aur aasani se badla nahi ja sakta." },
  { t: "MS Word", q: "Document par password kaise lagayein?", a: "File → Info → Protect Document → Encrypt with Password." },
  { t: "MS Word", q: "Format Painter kya karta hai?", a: "Ek jagah ki sajawat (font, rang, size) doosri jagah copy kar deta hai. Double click karein to kai jagah laga sakte hain." },
  { t: "MS Word", q: "Superscript aur Subscript ka shortcut?", a: "Superscript = Ctrl + Shift + + , Subscript = Ctrl + =" },
  { t: "MS Word", q: "Word me Undo kitni baar ho sakta hai?", a: "Kai baar — Ctrl+Z baar-baar dabate rahein. Wapas laane ke liye Ctrl+Y." },
  { t: "MS Word", q: "Word me ek shabd chunne ka tareeka?", a: "Us par double click. Poora paragraph chahiye to teen baar click." },
  { t: "MS Word", q: "Poora document chunne ka shortcut?", a: "Ctrl + A" },
  { t: "MS Word", q: "Font size badalne ka shortcut?", a: "Ctrl + ] bada karne ke liye, Ctrl + [ chhota karne ke liye." },
  { t: "MS Word", q: "Hindi typing Word me kaise karein?", a: "Windows me Hindi keyboard (Mangal/Inscript) add karein, fir Windows+Space se bhasha badlein. Font Mangal ya Kruti Dev rakhein." },
  { t: "MS Word", q: "Kruti Dev aur Mangal me farq?", a: "Mangal Unicode hai — har jagah sahi dikhta hai aur search hota hai. Kruti Dev purana font hai, doosre computer par toot sakta hai. Sarkari kaam me Mangal maanga jaata hai." },
  { t: "MS Word", q: "Hyperlink kaise lagate hain?", a: "Text chunkar Ctrl + K, fir link daal dein." },
  { t: "MS Word", q: "Ruler kis kaam aata hai?", a: "Indent aur tab set karne ke liye. View → Ruler se dikha sakte hain." },
  { t: "MS Word", q: "Indent kya hota hai?", a: "Paragraph ko margin se andar khiskana. Pehli line ka indent alag se set kiya ja sakta hai." },
  { t: "MS Word", q: "Drop Cap kya hai?", a: "Paragraph ka pehla akshar bada karke sajaana — magazine aur invitation me dikhta hai." },
  { t: "MS Word", q: "Columns kaise banate hain?", a: "Layout → Columns → 2 ya 3 chunein. Newsletter aur pamphlet ke liye." },
  { t: "MS Word", q: "Print me sirf kuch page kaise chhapein?", a: "Ctrl+P me Pages box me likhein — jaise 2-5 ya 1,3,7." },
  { t: "MS Word", q: "Ek page par do page kaise chhapein?", a: "Print settings me 'Pages per sheet' me 2 chunein — kagaz bachta hai." },
  { t: "MS Word", q: "Template kya hai?", a: "Pehle se bana banaya design jise bhar kar document taiyaar ho jaata hai — resume, letterhead, invoice." },
  { t: "MS Word", q: "AutoCorrect kya karta hai?", a: "Aam typing galtiyan apne aap sudhaar deta hai — 'teh' ko 'the' bana dena." },
  { t: "MS Word", q: "Word me shortcut se date kaise daalein?", a: "Alt + Shift + D — aaj ki date aa jaati hai. Time ke liye Alt + Shift + T." },
  { t: "MS Word", q: "Read Mode kis kaam aata hai?", a: "Sirf padhne ke liye saaf view — edit ke button chhup jaate hain, aankhon par zor kam padta hai." },
  { t: "MS Word", q: "Word file kharab ho jaye to?", a: "File → Open me file chunkar Open button ke arrow se 'Open and Repair' chunein." },
  { t: "MS Word", q: "Office me file apne aap save ho, iske liye?", a: "File → Options → Save me AutoRecover ka samay 5 minute kar dein." },

  /* ---------------- PowerPoint (40) ---------------- */
  { t: "PowerPoint", q: "PowerPoint kis kaam aata hai?", a: "Presentation banane ke liye — slide par point, photo aur chart dikhakar apni baat samjhane ke liye." },
  { t: "PowerPoint", q: "PowerPoint file ka extension?", a: ".pptx. Seedha chalne wali file .ppsx hoti hai." },
  { t: "PowerPoint", q: "Slide kya hoti hai?", a: "Presentation ka ek page. Sabhi slide milkar poori presentation banati hain." },
  { t: "PowerPoint", q: "Nayi slide jodne ka shortcut?", a: "Ctrl + M" },
  { t: "PowerPoint", q: "Slide show shuru karne ki key?", a: "F5 — pehli slide se. Maujooda slide se shuru karna ho to Shift + F5." },
  { t: "PowerPoint", q: "Slide show band karne ki key?", a: "Esc" },
  { t: "PowerPoint", q: "Slide Layout kya hai?", a: "Slide par title aur content kis jagah aayenge, uska tayyar design — Title Slide, Title and Content wagairah." },
  { t: "PowerPoint", q: "Slide Master kis kaam aata hai?", a: "Ek jagah design badal kar saari slides ka look ek saath badalne ke liye — logo aur font har slide par lagane me." },
  { t: "PowerPoint", q: "Theme kya hai?", a: "Rang, font aur design ka tayyar set jo poori presentation par ek jaisa look laata hai." },
  { t: "PowerPoint", q: "Transition kya hai?", a: "Ek slide se doosri slide par jaate waqt ka effect — jaise Fade, Push." },
  { t: "PowerPoint", q: "Animation kya hai?", a: "Slide ke andar ki cheezon par effect — jaise point ek-ek karke aana." },
  { t: "PowerPoint", q: "Transition aur Animation me farq?", a: "Transition slide badalne par lagta hai, Animation slide ke andar ki cheez par." },
  { t: "PowerPoint", q: "Speaker Notes kya hote hain?", a: "Har slide ke neeche aapke apne note — audience ko nahi dikhte, sirf aapki screen par." },
  { t: "PowerPoint", q: "Presenter View kya hai?", a: "Aapko notes, agli slide aur timer dikhta hai, jabki projector par sirf slide jaati hai." },
  { t: "PowerPoint", q: "Slide Sorter view kis kaam aata hai?", a: "Saari slides chhoti karke ek saath dikhata hai — kram badalna aasan ho jaata hai." },
  { t: "PowerPoint", q: "Slide chhupane ka tareeka?", a: "Slide par right click → Hide Slide. Wo show me nahi aayegi par file me rahegi." },
  { t: "PowerPoint", q: "Presentation me video kaise daalein?", a: "Insert → Video → This Device se apne computer ki video chunein." },
  { t: "PowerPoint", q: "Audio kaise jodte hain?", a: "Insert → Audio → Audio on My PC. Chaahein to background music poore show me chala sakte hain." },
  { t: "PowerPoint", q: "Chart kaise banate hain?", a: "Insert → Chart → prakar chunein, fir khulne wali chhoti Excel sheet me data bharein." },
  { t: "PowerPoint", q: "Presentation ko video kaise banayein?", a: "File → Export → Create a Video. WhatsApp par bhejne ke liye ye behtar rehta hai." },
  { t: "PowerPoint", q: "Rehearse Timings kya karta hai?", a: "Har slide par aapne kitna waqt liya, wo record karta hai — practice ke liye bahut upyogi." },
  { t: "PowerPoint", q: "Slide show apne aap chale, iske liye?", a: "Transitions me 'After' ka samay set karein aur 'On Mouse Click' hata dein." },
  { t: "PowerPoint", q: "Hyperlink slide me kaise lagayein?", a: "Text ya button chunkar Ctrl + K — doosri slide ya website se jod sakte hain." },
  { t: "PowerPoint", q: "Action Button kya hai?", a: "Slide par lagne wala button jisse Next, Previous ya kisi khaas slide par ja sakte hain." },
  { t: "PowerPoint", q: "Ek achhi slide me kitne point hone chahiye?", a: "6 se zyada nahi, aur har point 6-7 shabd ka. Slide par bhashan nahi, ishara hona chahiye." },
  { t: "PowerPoint", q: "Presentation me font kitna bada rakhein?", a: "Title 36-44, content 24-28. Peechhe baithe insaan ko dikhna chahiye." },
  { t: "PowerPoint", q: "Slide par kitne rang istemaal karein?", a: "2-3 se zyada nahi. Zyada rang se dhyan bat jaata hai aur look sasta lagta hai." },
  { t: "PowerPoint", q: "Presentation kitni lambi honi chahiye?", a: "Ek slide par 1-2 minute ka niyam maanein. 10 minute ke liye 6-8 slide kaafi hain." },
  { t: "PowerPoint", q: "Slide me picture ka size kaise thik rakhein?", a: "Kone se kheenchein (corner handle), taaki tasveer khinch kar bigde nahi." },
  { t: "PowerPoint", q: "Cheezon ko seedha (align) kaise karein?", a: "Sab chunkar Shape Format → Align → Align Left/Center. Aankh se karne se hamesha tedha rehta hai." },
  { t: "PowerPoint", q: "Group karna kya hota hai?", a: "Kai cheezon ko jodkar ek bana dena, taaki wo saath me khiskein. Ctrl + G." },
  { t: "PowerPoint", q: "Slide me table kaise daalein?", a: "Insert → Table → row-column chunein." },
  { t: "PowerPoint", q: "Presentation ko PDF me kaise badlein?", a: "File → Save As → PDF. Handout baantne ke liye achha rehta hai." },
  { t: "PowerPoint", q: "Handout kya hai?", a: "Ek kagaz par kai slides chhap kar audience ko dena. Print settings me Handout chunein." },
  { t: "PowerPoint", q: "Slide number kaise dikhayein?", a: "Insert → Slide Number → 'Slide number' par tick → Apply to All." },
  { t: "PowerPoint", q: "Presentation par password kaise lagayein?", a: "File → Info → Protect Presentation → Encrypt with Password." },
  { t: "PowerPoint", q: "Show ke beech me screen kaali kaise karein?", a: "B dabayein (Black). W dabane par safed. Dobara dabane par wapas slide." },
  { t: "PowerPoint", q: "Show ke beech me kisi slide par seedha kaise jaayein?", a: "Slide ka number type karke Enter dabayein." },
  { t: "PowerPoint", q: "Slide par pen se likhne ka tareeka?", a: "Show ke dauraan Ctrl + P se pen chalu, Ctrl + E se rubber, Esc se band." },
  { t: "PowerPoint", q: "Presentation dete waqt sabse badi galti kya hoti hai?", a: "Slide ko padh kar sunana. Slide par sirf point ho, batana aapko khud hai — tabhi audience judti hai." }
,

  /* ---------------- MS Excel (70) ---------------- */
  { t: "MS Excel", q: "MS Excel kis kaam aata hai?", a: "Numbers ka hisaab, list rakhna, report aur chart banane ke liye. Accounts aur data entry ka sabse bada auzaar." },
  { t: "MS Excel", q: "Excel file ka extension?", a: ".xlsx. Macro wali file .xlsm hoti hai." },
  { t: "MS Excel", q: "Cell kya hai?", a: "Row aur column ke milne par bana dabba — jaise A1, B5. Isi me data likha jaata hai." },
  { t: "MS Excel", q: "Row aur Column me farq?", a: "Row aade (horizontal) hoti hai aur number se pehchani jaati hai. Column khadi (vertical) hoti hai aur akshar se." },
  { t: "MS Excel", q: "Ek sheet me kitni rows hoti hain?", a: "10,48,576 rows aur 16,384 columns (A se XFD tak)." },
  { t: "MS Excel", q: "Workbook aur Worksheet me farq?", a: "Workbook poori file hai. Worksheet uske andar ka ek page (Sheet1, Sheet2)." },
  { t: "MS Excel", q: "Formula hamesha kis chinh se shuru hota hai?", a: "= (barabar). Bina iske Excel use text samajh leta hai." },
  { t: "MS Excel", q: "Formula aur Function me farq?", a: "Formula aapka apna banaya hisaab hai (=A1+B1). Function Excel ka tayyar formula hai (=SUM(A1:B1))." },
  { t: "MS Excel", q: "SUM function kya karta hai?", a: "Chuni hui cell ka jod deta hai. =SUM(B2:B10)" },
  { t: "MS Excel", q: "AVERAGE ka kaam?", a: "Ausat nikalta hai. =AVERAGE(B2:B10)" },
  { t: "MS Excel", q: "MAX aur MIN kya karte hain?", a: "MAX sabse bada number deta hai, MIN sabse chhota. =MAX(B2:B20)" },
  { t: "MS Excel", q: "COUNT aur COUNTA me farq?", a: "COUNT sirf numbers ginta hai. COUNTA har bhari hui cell ginta hai, chahe usme naam ho ya number." },
  { t: "MS Excel", q: "COUNTIF kya karta hai?", a: "Shart ke hisaab se ginti karta hai. =COUNTIF(C2:C50,\"Pass\") — kitne pass hue." },
  { t: "MS Excel", q: "SUMIF kya karta hai?", a: "Shart ke hisaab se jodta hai. =SUMIF(A2:A50,\"Ara\",C2:C50) — sirf Ara ki sale ka total." },
  { t: "MS Excel", q: "IF function kaise kaam karta hai?", a: "=IF(shart, sach hone par, jhooth hone par). Jaise =IF(B2>=33,\"Pass\",\"Fail\")" },
  { t: "MS Excel", q: "Nested IF kya hai?", a: "IF ke andar IF — grade nikalne me. =IF(B2>=90,\"A\",IF(B2>=75,\"B\",\"C\"))" },
  { t: "MS Excel", q: "VLOOKUP kya karta hai?", a: "Ek table me kisi value ko dhundh kar uske saath wali jaankari le aata hai. =VLOOKUP(A2,Sheet2!A:C,3,FALSE)" },
  { t: "MS Excel", q: "VLOOKUP me FALSE kyun lagate hain?", a: "FALSE ka matlab bilkul sahi match chahiye. TRUE lagane par galat jawab aa sakta hai." },
  { t: "MS Excel", q: "VLOOKUP ki sabse badi kami?", a: "Wo sirf dayein taraf dekh sakta hai — jis column me dhundh rahe hain uske baayein ka data nahi la sakta." },
  { t: "MS Excel", q: "VLOOKUP ki jagah aajkal kya istemaal hota hai?", a: "XLOOKUP — wo dono taraf dekh sakta hai aur na milne par khud message de sakta hai." },
  { t: "MS Excel", q: "HLOOKUP kab kaam aata hai?", a: "Jab data aadi (horizontal) rakha ho — row me dhundhna ho." },
  { t: "MS Excel", q: "INDEX aur MATCH saath me kyun?", a: "Ye VLOOKUP se zyada lachila hai — kisi bhi taraf dekh sakta hai aur column badalne par toota nahi." },
  { t: "MS Excel", q: "CONCATENATE ya & kya karta hai?", a: "Do cell ka text jodta hai. =A2&\" \"&B2 se naam aur surname jud jaate hain." },
  { t: "MS Excel", q: "LEFT, RIGHT, MID kya karte hain?", a: "Text me se hissa nikalte hain — LEFT shuru se, RIGHT aakhir se, MID beech se." },
  { t: "MS Excel", q: "LEN function?", a: "Text me kitne akshar hain, wo ginta hai. Mobile number 10 ka hai ya nahi, ye check karne me kaam aata hai." },
  { t: "MS Excel", q: "TRIM kya karta hai?", a: "Text ke aage-peechhe ki fazool khali jagah hata deta hai — copy-paste ke baad bahut kaam aata hai." },
  { t: "MS Excel", q: "UPPER, LOWER, PROPER?", a: "UPPER sab bade akshar, LOWER sab chhote, PROPER har shabd ka pehla akshar bada." },
  { t: "MS Excel", q: "ROUND function?", a: "Number ko chune hue dashamlav tak gol karta hai. =ROUND(A2,2)" },
  { t: "MS Excel", q: "TODAY aur NOW me farq?", a: "TODAY sirf aaj ki date deta hai. NOW date ke saath samay bhi." },
  { t: "MS Excel", q: "Absolute reference kya hai?", a: "$ lagakar cell ko pakka karna, taaki formula kheenchne par wo na badle — jaise $B$1." },
  { t: "MS Excel", q: "F4 key formula me kya karti hai?", a: "Cell reference me $ lagati-hatati hai — relative se absolute karne ka sabse tez tareeka." },
  { t: "MS Excel", q: "Relative aur Absolute reference me farq?", a: "Relative formula kheenchne par badal jaata hai (A1 se A2). Absolute waisa hi rehta hai ($A$1)." },
  { t: "MS Excel", q: "#DIV/0! error kab aata hai?", a: "Jab kisi number ko 0 se bhaag diya ho ya khali cell se." },
  { t: "MS Excel", q: "#N/A error ka matlab?", a: "VLOOKUP jaise function ko dhundhi hui cheez mili hi nahi." },
  { t: "MS Excel", q: "#VALUE! error kyun aata hai?", a: "Jab number ki jagah text par hisaab karne ki koshish ho." },
  { t: "MS Excel", q: "#REF! error kab dikhta hai?", a: "Jab formula jis cell ko dekh raha tha wo delete ho gayi ho." },
  { t: "MS Excel", q: "Error chhupane ke liye kya karte hain?", a: "IFERROR lagate hain. =IFERROR(VLOOKUP(...),\"Nahi mila\")" },
  { t: "MS Excel", q: "Freeze Panes kya karta hai?", a: "Upar ki heading row ko chipka deta hai, taaki neeche scroll karne par bhi wo dikhti rahe. View → Freeze Panes." },
  { t: "MS Excel", q: "Filter kis kaam aata hai?", a: "Bade data me se sirf matlab ki row dikhane ke liye. Ctrl + Shift + L." },
  { t: "MS Excel", q: "Sort kya karta hai?", a: "Data ko kram me lagata hai — A se Z, chhote se bade, ya date ke hisaab se." },
  { t: "MS Excel", q: "Conditional Formatting kya hai?", a: "Shart ke hisaab se cell ka rang badalna — jaise 33 se kam marks laal ho jayein." },
  { t: "MS Excel", q: "Data Validation kis kaam aata hai?", a: "Cell me sirf sahi cheez bharne dena — jaise sirf 0-100 ke beech ka number, ya ek banai hui list." },
  { t: "MS Excel", q: "Drop-down list kaise banate hain?", a: "Data → Data Validation → Allow me List chunkar options likh dein." },
  { t: "MS Excel", q: "Pivot Table kya hai?", a: "Bade data ka summary turant banane ka auzaar — kaunse sheher me kitni sale hui, ek click me." },
  { t: "MS Excel", q: "Pivot Table kab istemaal karte hain?", a: "Jab hazaron row ka data ho aur usme se matlab nikalna ho, bina formula likhe." },
  { t: "MS Excel", q: "Chart kaise banate hain?", a: "Data chunkar Insert → Chart → prakar chunein. Ya Alt + F1 se turant chart." },
  { t: "MS Excel", q: "Pie chart kab istemaal karein?", a: "Jab hisse dikhane hon — kul ka kitna pratishat kis cheez ka hai. 5-6 se zyada hisse hon to pie theek nahi lagta." },
  { t: "MS Excel", q: "Bar aur Line chart me farq?", a: "Bar cheezon ki tulna dikhata hai. Line samay ke saath badlav dikhata hai." },
  { t: "MS Excel", q: "Print me har page par heading kaise aaye?", a: "Page Layout → Print Titles → 'Rows to repeat at top' me heading row chunein." },
  { t: "MS Excel", q: "Poori sheet ek page par kaise chhapein?", a: "Print settings me 'Fit Sheet on One Page' chunein." },
  { t: "MS Excel", q: "Print area kya hoti hai?", a: "Sheet ka wo hissa jo chhapega. Chunkar Page Layout → Print Area → Set." },
  { t: "MS Excel", q: "Cell me nayi line kaise daalein?", a: "Alt + Enter" },
  { t: "MS Excel", q: "Aaj ki date ka shortcut?", a: "Ctrl + ; (semicolon). Samay ke liye Ctrl + Shift + ;" },
  { t: "MS Excel", q: "Upar wali cell ka data neeche copy karne ka shortcut?", a: "Ctrl + D (Fill Down). Baayein se dayein ke liye Ctrl + R." },
  { t: "MS Excel", q: "Data ke aakhir tak jaane ka shortcut?", a: "Ctrl + neeche arrow. Poora chunna ho to Ctrl + Shift + neeche arrow." },
  { t: "MS Excel", q: "A1 par wapas jaane ka shortcut?", a: "Ctrl + Home" },
  { t: "MS Excel", q: "Nayi sheet jodne ka shortcut?", a: "Shift + F11" },
  { t: "MS Excel", q: "Sheet ke beech badalne ka shortcut?", a: "Ctrl + Page Up / Page Down" },
  { t: "MS Excel", q: "Format Cells dialog ka shortcut?", a: "Ctrl + 1" },
  { t: "MS Excel", q: "Paste Special kis kaam aata hai?", a: "Sirf value, sirf formula, ya sirf format paste karne ke liye. Ctrl + Alt + V." },
  { t: "MS Excel", q: "Formula ki jagah sirf value kaise rakhein?", a: "Copy karke Paste Special → Values. Isse formula hat jaata hai aur sirf natija rehta hai." },
  { t: "MS Excel", q: "Transpose kya karta hai?", a: "Row ko column me aur column ko row me badal deta hai — Paste Special me option hai." },
  { t: "MS Excel", q: "Text to Columns kab kaam aata hai?", a: "Jab ek cell me poora naam-pata ho aur use alag columns me todna ho." },
  { t: "MS Excel", q: "Remove Duplicates kya karta hai?", a: "Data me se dohri entries hata deta hai. Data tab me milta hai." },
  { t: "MS Excel", q: "Flash Fill kya hai?", a: "Ctrl + E — aap ek-do udaharan bhar dein, Excel baaki khud samajh kar bhar deta hai." },
  { t: "MS Excel", q: "Sheet ko chhupane ka tareeka?", a: "Sheet ke naam par right click → Hide. Wapas laane ke liye Unhide." },
  { t: "MS Excel", q: "Sheet par password kaise lagayein?", a: "Review → Protect Sheet. Poori file ke liye File → Info → Protect Workbook." },
  { t: "MS Excel", q: "Macro kya hai?", a: "Baar-baar hone wale kaam ko record karke ek button se chalana. File .xlsm me save karni padti hai." },
  { t: "MS Excel", q: "Excel me data entry me sabse aam galti kya hoti hai?", a: "Number ko text ki tarah bhar dena (aage space ya apostrophe ke saath) — fir SUM kaam nahi karta." },
  { t: "MS Excel", q: "Bade data me kaam karte waqt kya dhyan rakhein?", a: "Heading freeze karein, table format lagayein, backup rakhein, aur formula ke natije ko ek baar haath se milakar dekh lein." },

  /* ---------------- Internet & Email (50) ---------------- */
  { t: "Internet & Email", q: "Internet kya hai?", a: "Duniya bhar ke computers ka aapas me juda hua jaal, jisse data ek jagah se doosri jagah jaata hai." },
  { t: "Internet & Email", q: "WWW aur Internet me farq?", a: "Internet poora jaal hai. WWW us jaal par chalne wali websites ki sewa hai — Internet par email aur bahut kuch aur bhi hai." },
  { t: "Internet & Email", q: "Browser kya hai?", a: "Wo software jisse website kholte hain — Chrome, Edge, Firefox." },
  { t: "Internet & Email", q: "Search engine kya hai?", a: "Internet par cheezein dhundhne ka auzaar — Google, Bing." },
  { t: "Internet & Email", q: "URL kya hota hai?", a: "Website ka pata — jaise https://softskillzone.in" },
  { t: "Internet & Email", q: "Domain name kya hai?", a: "Website ka naam jo yaad rakhna aasan ho — softskillzone.in. Iske peechhe asal me ek IP address hota hai." },
  { t: "Internet & Email", q: "IP address kya hai?", a: "Har device ka internet par apna number — jaise 192.168.1.1" },
  { t: "Internet & Email", q: "DNS kya karta hai?", a: "Website ke naam ko IP address me badalta hai — internet ki phone directory jaisa." },
  { t: "Internet & Email", q: "HTTP aur HTTPS me farq?", a: "HTTPS me data encrypt hota hai, isliye surakshit hai. Payment kabhi bina HTTPS ke na karein." },
  { t: "Internet & Email", q: "Website par taala (lock) ka nishaan kya batata hai?", a: "Ki connection surakshit hai (HTTPS). Par iska matlab ye nahi ki website imaandaar hai." },
  { t: "Internet & Email", q: "Download aur Upload me farq?", a: "Download — internet se apne device par laana. Upload — apne device se internet par bhejna." },
  { t: "Internet & Email", q: "Bandwidth kya hai?", a: "Ek samay me kitna data aa-ja sakta hai. Zyada bandwidth matlab tez internet." },
  { t: "Internet & Email", q: "Wi-Fi aur LAN me farq?", a: "LAN taar se jodta hai — zyada tez aur bharosemand. Wi-Fi bina taar ke — zyada aaram se chalta hai." },
  { t: "Internet & Email", q: "Router ka kaam?", a: "Ek internet connection ko kai devices me baantta hai." },
  { t: "Internet & Email", q: "Modem kya karta hai?", a: "Internet ke signal ko computer ke samajhne layak banata hai, aur ulta bhi." },
  { t: "Internet & Email", q: "Email ka poora naam?", a: "Electronic Mail" },
  { t: "Internet & Email", q: "Email address ke do hisse kaunse hain?", a: "@ se pehle username, @ ke baad domain — jaise info@softskillzone.in" },
  { t: "Internet & Email", q: "To, CC aur BCC me farq?", a: "To — jise mail hai. CC — jankari ke liye copy, sabko dikhta hai. BCC — chhupi copy, doosron ko nahi dikhti." },
  { t: "Internet & Email", q: "BCC kab istemaal karte hain?", a: "Jab kai logon ko ek saath mail bhejni ho par unke email ek doosre ko na dikhein." },
  { t: "Internet & Email", q: "Reply aur Reply All me farq?", a: "Reply sirf bhejne wale ko jaata hai. Reply All sabhi ko — galti se dabane par sharmindagi ho sakti hai." },
  { t: "Internet & Email", q: "Forward kya karta hai?", a: "Aayi hui mail ko kisi teesre insaan ko aage bhejna." },
  { t: "Internet & Email", q: "Attachment kya hai?", a: "Mail ke saath judi hui file — document, photo ya PDF." },
  { t: "Internet & Email", q: "Bahut badi file email se kaise bhejein?", a: "Google Drive par upload karke link bhejein. Gmail me 25 MB se badi file waise bhi nahi jaati." },
  { t: "Internet & Email", q: "Spam kya hai?", a: "Bin maangi, aksar dhokebaaz mail. Usme diye link par kabhi click na karein." },
  { t: "Internet & Email", q: "Phishing kya hoti hai?", a: "Nakli mail ya website se aapka password ya bank detail nikalwane ki koshish — bank ki tarah dikh kar." },
  { t: "Internet & Email", q: "Phishing mail kaise pehchanein?", a: "Bhejne wale ka pata galat hota hai, jaldi machayi jaati hai, aur link ka pata asli site se milta-julta par alag hota hai." },
  { t: "Internet & Email", q: "Strong password kaisa hota hai?", a: "Kam se kam 12 akshar, bade-chhote akshar, number aur chinh — aur har site par alag." },
  { t: "Internet & Email", q: "Two-factor authentication kya hai?", a: "Password ke saath ek aur pehchaan — phone par aaya OTP ya app ka code. Password chori hone par bhi account bacha rehta hai." },
  { t: "Internet & Email", q: "Email signature kya hai?", a: "Har mail ke neeche apne aap lagne wala naam, pad aur contact — professional lagta hai." },
  { t: "Internet & Email", q: "Draft folder kis kaam aata hai?", a: "Adhoori likhi hui mail wahan apne aap save hoti rehti hai." },
  { t: "Internet & Email", q: "Google Drive kya hai?", a: "Google ka cloud storage — files internet par rakhein aur kahin se bhi kholein." },
  { t: "Internet & Email", q: "Google Docs ka faayda?", a: "Bina software ke browser me document banayein, apne aap save hota hai, aur kai log ek saath edit kar sakte hain." },
  { t: "Internet & Email", q: "Google Sheets kya hai?", a: "Excel jaisa online spreadsheet — muft aur milkar kaam karne ke liye behtareen." },
  { t: "Internet & Email", q: "Google Forms kis kaam aata hai?", a: "Online form banane ke liye — admission enquiry, feedback, quiz. Jawab apne aap Sheet me aa jaate hain." },
  { t: "Internet & Email", q: "Google Meet kya hai?", a: "Video meeting ka auzaar — online class lene ke liye istemaal hota hai." },
  { t: "Internet & Email", q: "Google Calendar ka faayda?", a: "Class aur meeting ka samay set karke pehle se reminder mil jaata hai." },
  { t: "Internet & Email", q: "File share karte waqt permission ka dhyan kyun?", a: "Galti se 'Anyone with link can edit' rakhne par koi bhi aapka data badal sakta hai. 'Viewer' rakhna surakshit hai." },
  { t: "Internet & Email", q: "Cookie kya hoti hai?", a: "Website ki rakhi hui chhoti file jo aapko yaad rakhti hai — login aur pasand." },
  { t: "Internet & Email", q: "Cache clear karne se kya hota hai?", a: "Browser ki purani rakhi hui files hat jaati hain — website ki dikkat aksar isi se theek ho jaati hai." },
  { t: "Internet & Email", q: "Incognito mode kya karta hai?", a: "Browser aapki history nahi rakhta. Par internet company aur website aapko phir bhi dekh sakti hai." },
  { t: "Internet & Email", q: "Bookmark kya hai?", a: "Website ko save kar lena taaki dobara pata na likhna pade. Ctrl + D." },
  { t: "Internet & Email", q: "Browser me naya tab kholne ka shortcut?", a: "Ctrl + T. Band karne ke liye Ctrl + W, band hua tab wapas Ctrl + Shift + T." },
  { t: "Internet & Email", q: "Web page ko PDF kaise save karein?", a: "Ctrl + P → Destination me 'Save as PDF' chunein." },
  { t: "Internet & Email", q: "Video call me internet slow ho to?", a: "Video band karke sirf audio rakhein, doosre download rokein, aur router ke paas aa jaayein." },
  { t: "Internet & Email", q: "Public Wi-Fi par kya nahi karna chahiye?", a: "Net banking aur payment — wahan data churaya ja sakta hai." },
  { t: "Internet & Email", q: "Digital signature kya hai?", a: "Document par lagne wali electronic pehchaan jo sabit karti hai ki wo aapne bheja hai aur badla nahi gaya." },
  { t: "Internet & Email", q: "e-Governance ke do udaharan?", a: "Income Tax e-filing aur GST portal — sarkari kaam online karna." },
  { t: "Internet & Email", q: "UPI kya hai?", a: "Unified Payments Interface — mobile se turant paisa bhejne ka Indian system. PhonePe, GPay isi par chalte hain." },
  { t: "Internet & Email", q: "OTP kisi ko batana kyun galat hai?", a: "OTP hi aakhri taala hai. Bank kabhi OTP nahi maangta — jo maange wo dhokebaaz hai." },
  { t: "Internet & Email", q: "Office me internet ka sahi istemaal kya hai?", a: "Kaam se juda hi istemaal, bina jaane software download na karna, aur har mail ka link soch kar kholna." }
,

  /* ---------------- Tally & Accounts (65) ---------------- */
  { t: "Tally & Accounts", q: "Accounting kya hai?", a: "Business ke har paise ke len-den ko tarteeb se likhna, taaki laabh-haani aur sthiti saaf pata chale." },
  { t: "Tally & Accounts", q: "Journal entry kya hoti hai?", a: "Kisi len-den ki pehli likhat — kaunsa khata debit hua aur kaunsa credit." },
  { t: "Tally & Accounts", q: "Debit aur Credit ka aam niyam?", a: "Jo aata hai wo debit, jo jaata hai wo credit. Kharcha debit, aamdani credit." },
  { t: "Tally & Accounts", q: "Ledger kya hai?", a: "Ek khaate ka poora hisaab ek jagah — jaise 'Ram Traders' ka saara len-den." },
  { t: "Tally & Accounts", q: "Trial Balance kya batata hai?", a: "Saare khaton ke debit aur credit ka jod. Dono barabar na hon to kahin galti hai." },
  { t: "Tally & Accounts", q: "Balance Sheet kya dikhati hai?", a: "Ek tareekh par business ke paas kya hai (assets) aur kiska dena hai (liabilities)." },
  { t: "Tally & Accounts", q: "Profit & Loss account kya batata hai?", a: "Ek awadhi me kitni aamdani hui aur kitna kharcha — natija laabh ya haani." },
  { t: "Tally & Accounts", q: "Asset aur Liability me farq?", a: "Asset — jo business ke paas hai (cash, machine). Liability — jo business ko dena hai (loan, creditors)." },
  { t: "Tally & Accounts", q: "Capital kya hai?", a: "Maalik ne business me jo paisa lagaya. Ye business ke liye ek liability hoti hai." },
  { t: "Tally & Accounts", q: "Drawings kya hai?", a: "Maalik ne apne niji kaam ke liye business se jo paisa nikala." },
  { t: "Tally & Accounts", q: "Debtor aur Creditor me farq?", a: "Debtor — jisse humein lena hai (customer). Creditor — jise humein dena hai (supplier)." },
  { t: "Tally & Accounts", q: "Cash aur Credit sale me farq?", a: "Cash sale me paisa turant milta hai. Credit sale me baad me — customer debtor ban jaata hai." },
  { t: "Tally & Accounts", q: "Depreciation kya hai?", a: "Machine ya gaadi ki keemat samay ke saath ghatna. Har saal kharche me dikhaya jaata hai." },
  { t: "Tally & Accounts", q: "Opening aur Closing stock?", a: "Opening — saal ke shuru ka maal. Closing — saal ke aakhir me bacha maal." },
  { t: "Tally & Accounts", q: "Tally Prime kya hai?", a: "India me sabse zyada istemaal hone wala accounting software — hisaab, stock, GST aur payroll sab isme." },
  { t: "Tally & Accounts", q: "Tally me company kaise banate hain?", a: "Gateway of Tally se Create Company, fir naam, pata, financial year aur base currency bharein." },
  { t: "Tally & Accounts", q: "Gateway of Tally kya hai?", a: "Tally ki main screen jahan se saare kaam shuru hote hain." },
  { t: "Tally & Accounts", q: "Tally me Ledger kaise banate hain?", a: "Gateway → Create → Ledger. Naam dein aur sahi 'Under' group chunein." },
  { t: "Tally & Accounts", q: "Group ka kya matlab hai Tally me?", a: "Milte-julte khaton ka parivaar — Sundry Debtors, Indirect Expenses. Report isi hisaab se banti hai." },
  { t: "Tally & Accounts", q: "Tally me kitne default groups hote hain?", a: "28 — jisme 15 primary aur 13 sub-groups hote hain." },
  { t: "Tally & Accounts", q: "Voucher kya hai?", a: "Har len-den ki entry ka form — payment, receipt, sales, purchase wagairah." },
  { t: "Tally & Accounts", q: "Payment voucher ka shortcut?", a: "F5" },
  { t: "Tally & Accounts", q: "Receipt voucher ka shortcut?", a: "F6" },
  { t: "Tally & Accounts", q: "Contra voucher ka shortcut aur kaam?", a: "F4 — cash aur bank ke beech paisa idhar-udhar karne ke liye." },
  { t: "Tally & Accounts", q: "Journal voucher ka shortcut?", a: "F7 — adjustment entry ke liye." },
  { t: "Tally & Accounts", q: "Sales voucher ka shortcut?", a: "F8" },
  { t: "Tally & Accounts", q: "Purchase voucher ka shortcut?", a: "F9" },
  { t: "Tally & Accounts", q: "Debit Note kab banate hain?", a: "Jab kharida hua maal wapas karein ya supplier se kam paisa dena ho." },
  { t: "Tally & Accounts", q: "Credit Note kab banate hain?", a: "Jab becha hua maal wapas aaye ya customer ko chhoot deni ho." },
  { t: "Tally & Accounts", q: "Contra entry ka udaharan dijiye.", a: "Bank se cash nikalna, ya cash bank me jama karna." },
  { t: "Tally & Accounts", q: "Tally me Stock Item kaise banate hain?", a: "Create → Stock Item. Uske Unit aur Stock Group bhi pehle bana lena chahiye." },
  { t: "Tally & Accounts", q: "Godown kya hai Tally me?", a: "Alag-alag jagah rakhe stock ka hisaab rakhne ke liye — dukaan aur gaddi alag." },
  { t: "Tally & Accounts", q: "Unit of Measure kya hai?", a: "Maal kis ikai me ginte hain — Nos, Kg, Ltr, Box." },
  { t: "Tally & Accounts", q: "Bank Reconciliation kya hai?", a: "Apni bank book ko bank ke statement se milana, taaki farq ki wajah pata chale." },
  { t: "Tally & Accounts", q: "Day Book kya dikhati hai?", a: "Ek din ki saari entries ek jagah. Gateway → Display → Day Book." },
  { t: "Tally & Accounts", q: "Tally me report ka period kaise badlein?", a: "Alt + F2 se — kaunsi tareekh se kaunsi tak dekhna hai." },
  { t: "Tally & Accounts", q: "Tally me company badalne ka shortcut?", a: "Alt + F3 (Company info) me se Select/Shut Company." },
  { t: "Tally & Accounts", q: "Tally me data ka backup kaise lein?", a: "Company Info → Backup, aur destination folder chunein. Har hafte lena chahiye." },
  { t: "Tally & Accounts", q: "Tally ka data folder ka naam kaise dikhta hai?", a: "Har company ka apna number wala folder banta hai (jaise 10001) Tally ke data folder ke andar." },
  { t: "Tally & Accounts", q: "Tally Vault kya hai?", a: "Company par password lagakar data ko encrypt karna. Password bhoolne par data wapas nahi milta." },
  { t: "Tally & Accounts", q: "Security Control kis kaam aata hai?", a: "Alag-alag user ko alag-alag adhikar dena — jaise accountant sirf entry kare, report na badle." },
  { t: "Tally & Accounts", q: "Cost Centre kya hai?", a: "Kharche ko vibhag ya project ke hisaab se baantna — kaunsi branch me kitna kharch hua." },
  { t: "Tally & Accounts", q: "Budget Tally me kis kaam aata hai?", a: "Pehle se kharche ki seema tay karke asli kharche se milana." },
  { t: "Tally & Accounts", q: "Payroll Tally me kya karta hai?", a: "Karamchariyon ki salary, attendance, PF aur ESI ka hisaab." },
  { t: "Tally & Accounts", q: "Outstanding report kya batati hai?", a: "Kis customer se kitna lena baaki hai aur kis supplier ko kitna dena." },
  { t: "Tally & Accounts", q: "Ageing analysis kya hai?", a: "Bakaya paisa kitne din purana hai — 30, 60, 90 din. Vasooli me bahut kaam aata hai." },
  { t: "Tally & Accounts", q: "Tally se report Excel me kaise le jaayein?", a: "Report kholkar Alt + E (Export) → format me Excel chunein." },
  { t: "Tally & Accounts", q: "Tally me entry delete kaise karein?", a: "Voucher kholkar Alt + D. Par delete karne se pehle soch lein — record khatam ho jaata hai." },
  { t: "Tally & Accounts", q: "Tally me galti se ki hui entry kaise theek karein?", a: "Day Book me se voucher kholein, sudhaar karein aur Enter se accept kar dein." },
  { t: "Tally & Accounts", q: "Tally me F11 aur F12 me farq?", a: "F11 = Features (company ke liye feature on/off). F12 = Configuration (screen kaise dikhe)." },
  { t: "Tally & Accounts", q: "Multi-currency kab chalu karte hain?", a: "Jab bahar ke desh se len-den ho — F11 se chalu karke currency banate hain." },
  { t: "Tally & Accounts", q: "Bill-wise details kya hai?", a: "Har bill ka alag hisaab rakhna, taaki pata chale kaunsa bill baaki hai aur kaunsa chuk gaya." },
  { t: "Tally & Accounts", q: "Interest calculation Tally me?", a: "F11 me chalu karke ledger par byaaj ki dar set karein — der se payment par byaaj apne aap." },
  { t: "Tally & Accounts", q: "TDS Tally me kaise handle hota hai?", a: "F11 me TDS chalu karke nature of payment aur deductee type set karte hain, fir voucher me TDS apne aap katta hai." },
  { t: "Tally & Accounts", q: "Purchase Order aur Sales Order kya hain?", a: "Maal mangwane aur bechne ka pehle se bana order. Baad me usi se bill ban jaata hai." },
  { t: "Tally & Accounts", q: "Delivery Note kya hai?", a: "Maal bhejte waqt ka kagaz. Bill baad me banta hai." },
  { t: "Tally & Accounts", q: "Receipt Note kis kaam aata hai?", a: "Maal aane par uski entry — bill baad me aaye tab bhi stock sahi rehta hai." },
  { t: "Tally & Accounts", q: "Stock Summary kya dikhati hai?", a: "Kaunsa maal kitna bacha hai aur uski keemat kitni hai." },
  { t: "Tally & Accounts", q: "Negative stock kyun dikhta hai?", a: "Jab bina purchase entry ke sale kar di jaye. Purchase entry karte hi theek ho jaata hai." },
  { t: "Tally & Accounts", q: "FIFO kya hai?", a: "First In First Out — jo maal pehle aaya wo pehle bika, aise stock ki keemat lagti hai." },
  { t: "Tally & Accounts", q: "Tally Prime aur Tally ERP 9 me bada farq?", a: "Tally Prime ka look naya hai, kisi bhi report par 'Go To' se seedha ja sakte hain, aur multi-tasking behtar hai." },
  { t: "Tally & Accounts", q: "Accounting me 'Golden Rules' kitne hain?", a: "Teen — Personal, Real aur Nominal account ke liye alag-alag." },
  { t: "Tally & Accounts", q: "Nominal account ka niyam?", a: "Saare kharche aur nuksaan debit, saari aamdani aur laabh credit." },
  { t: "Tally & Accounts", q: "Real account ka niyam?", a: "Jo aaye wo debit, jo jaaye wo credit." },
  { t: "Tally & Accounts", q: "Ek accountant me kaunsi khoobi sabse zaroori hai?", a: "Sahi hona aur imaandaari. Ek galat entry poori balance sheet bigaad deti hai, aur bharosa hi is kaam ki asli poonji hai." },

  /* ---------------- GST & Tax (50) ---------------- */
  { t: "GST & Tax", q: "GST ka poora naam?", a: "Goods and Services Tax — vastu evam sewa kar." },
  { t: "GST & Tax", q: "GST kab lagu hua?", a: "1 July 2017 se poore Bharat me." },
  { t: "GST & Tax", q: "GST ka mool siddhant kya hai?", a: "Ek desh, ek kar. Isse pehle ke kai tax (VAT, Service Tax, Excise) iske andar aa gaye." },
  { t: "GST & Tax", q: "GST ke kitne prakar hain?", a: "Chaar — CGST, SGST, IGST aur UTGST." },
  { t: "GST & Tax", q: "CGST aur SGST kab lagta hai?", a: "Jab kharid-bikri ek hi rajya me ho. Tax aadha kendra ko, aadha rajya ko." },
  { t: "GST & Tax", q: "IGST kab lagta hai?", a: "Jab maal ek rajya se doosre rajya jaaye. Poora tax kendra leta hai aur baad me baant deta hai." },
  { t: "GST & Tax", q: "GSTIN kya hai?", a: "15 anko ka GST number. Pehle 2 ank rajya ka code, agle 10 PAN, fir entity number, blank aur check digit." },
  { t: "GST & Tax", q: "Bihar ka GST state code?", a: "10" },
  { t: "GST & Tax", q: "GST registration kab zaroori hai?", a: "Maal ke liye 40 lakh aur sewa ke liye 20 lakh salana turnover ke upar (kuch rajyon me seema kam hai)." },
  { t: "GST & Tax", q: "Composition scheme kya hai?", a: "Chhote vyapari kam dar par seedha tax de sakte hain, par unhe input credit nahi milta aur wo tax vasool nahi kar sakte." },
  { t: "GST & Tax", q: "Input Tax Credit (ITC) kya hai?", a: "Kharid par diya hua GST, bikri ke GST me se ghata dena. Isse ek hi cheez par baar-baar tax nahi lagta." },
  { t: "GST & Tax", q: "ITC kab nahi milta?", a: "Jab supplier ne tax jama na kiya ho, ya cheez blocked list me ho — jaise niji gaadi ya khana-peena." },
  { t: "GST & Tax", q: "GST ki dar kaun si hain?", a: "Mukhya slabs — 0%, 5%, 12%, 18% aur 28%. Kuch cheezon par cess bhi lagta hai." },
  { t: "GST & Tax", q: "HSN code kya hai?", a: "Maal ki pehchaan ka antarrashtriya code, jisse GST ki dar tay hoti hai." },
  { t: "GST & Tax", q: "SAC code kya hai?", a: "Sewaon ke liye code — jaise HSN maal ke liye hota hai." },
  { t: "GST & Tax", q: "Tax invoice me kya-kya hona chahiye?", a: "Bechne wale ka GSTIN, invoice number aur date, kharidar ki detail, HSN, maal ka vivaran, dar aur tax ka alag-alag hisaab." },
  { t: "GST & Tax", q: "Bill of Supply kab banta hai?", a: "Jab tax na lag raha ho — composition dealer ya exempt maal par." },
  { t: "GST & Tax", q: "E-way bill kab zaroori hai?", a: "50,000 rupaye se upar ka maal ek jagah se doosri jagah bhejte waqt." },
  { t: "GST & Tax", q: "E-way bill kitne din chalta hai?", a: "Aam gaadi me har 200 km ke liye ek din. Doori zyada ho to zyada din." },
  { t: "GST & Tax", q: "GSTR-1 kya hai?", a: "Bikri (outward supply) ka vivaran — mahine ya tinmahi me bharna hota hai." },
  { t: "GST & Tax", q: "GSTR-3B kya hai?", a: "Sankshipt masik return jisme tax ka hisaab lagakar payment kiya jaata hai." },
  { t: "GST & Tax", q: "GSTR-2B kya hai?", a: "Aapko milne wale input credit ka apne aap bana hua statement — supplier ki GSTR-1 se banta hai." },
  { t: "GST & Tax", q: "GSTR-9 kya hai?", a: "Salana return, jo saal bhar ke saare return ka nichod hota hai." },
  { t: "GST & Tax", q: "GSTR-3B bharne ki aakhri tareekh?", a: "Aam taur par agle mahine ki 20 tareekh (QRMP me alag)." },
  { t: "GST & Tax", q: "Return der se bharne par kya hota hai?", a: "Late fee lagti hai aur bakaya tax par byaaj bhi." },
  { t: "GST & Tax", q: "QRMP scheme kya hai?", a: "5 crore tak turnover wale return tinmahi bhar sakte hain par tax har mahine dena hota hai." },
  { t: "GST & Tax", q: "Reverse Charge kya hai?", a: "Jab tax bechne wale ki jagah kharidne wale ko bharna padta hai." },
  { t: "GST & Tax", q: "Nil return kya hai?", a: "Jab mahine me koi len-den na ho, tab bhi khali return bharna zaroori hai." },
  { t: "GST & Tax", q: "GST me Debit Note kab jaari hota hai?", a: "Jab bill me keemat ya tax kam lag gaya ho aur badhana ho." },
  { t: "GST & Tax", q: "GST me Credit Note kab jaari hota hai?", a: "Jab maal wapas aaye ya bill me keemat zyada lag gayi ho." },
  { t: "GST & Tax", q: "Exempt aur Zero-rated me farq?", a: "Exempt par tax nahi aur ITC bhi nahi. Zero-rated (export) par tax 0 hai par ITC mil jaata hai." },
  { t: "GST & Tax", q: "Export par GST kaise lagta hai?", a: "Export zero-rated hai. Ya to LUT lekar bina tax bhejein, ya tax dekar refund lein." },
  { t: "GST & Tax", q: "Tally me GST kaise chalu karte hain?", a: "F11 → Statutory → GST par Yes, fir GSTIN, rajya aur registration type bharein." },
  { t: "GST & Tax", q: "Tally me GST ki dar kahan set hoti hai?", a: "Stock Item ya Stock Group par GST Details me — HSN aur dar dono." },
  { t: "GST & Tax", q: "Tally me GSTR-1 report kahan milti hai?", a: "Gateway → Display → Statutory Reports → GST → GSTR-1." },
  { t: "GST & Tax", q: "Income Tax kis par lagta hai?", a: "Vyakti ya sanstha ki saal bhar ki aamdani par." },
  { t: "GST & Tax", q: "PAN kya hai?", a: "Permanent Account Number — 10 anko-akshar ka number jo har tax bharne wale ke paas hona chahiye." },
  { t: "GST & Tax", q: "Assessment Year aur Financial Year me farq?", a: "Financial Year jisme kamai hui (2025-26). Assessment Year uske agle saal (2026-27) jisme uska tax bharte hain." },
  { t: "GST & Tax", q: "ITR kya hai?", a: "Income Tax Return — saal bhar ki aamdani aur tax ka byora jo sarkar ko dete hain." },
  { t: "GST & Tax", q: "Form 16 kya hai?", a: "Employer dwara diya gaya prapatra jisme salary aur kata hua TDS likha hota hai." },
  { t: "GST & Tax", q: "Form 26AS kya batata hai?", a: "Aapke PAN par jitna tax kata aur jama hua, uska poora hisaab." },
  { t: "GST & Tax", q: "TDS kya hai?", a: "Tax Deducted at Source — payment karte waqt hi tax kaat kar sarkar ko jama karna." },
  { t: "GST & Tax", q: "TDS kaun kaatta hai?", a: "Payment karne wala (deductor) kaat kar sarkar ko jama karta hai." },
  { t: "GST & Tax", q: "TAN kya hai?", a: "Tax Deduction Account Number — TDS kaatne walon ke liye zaroori 10 ank ka number." },
  { t: "GST & Tax", q: "TDS return kab bharna hota hai?", a: "Har tinmahi — aam taur par tinmahi khatam hone ke agle mahine ki 31 tareekh tak." },
  { t: "GST & Tax", q: "Form 16 aur 16A me farq?", a: "16 salary par kate TDS ke liye, 16A salary ke alawa (jaise contract, byaaj) par kate TDS ke liye." },
  { t: "GST & Tax", q: "Advance Tax kya hai?", a: "Saal ke aakhir me ek saath dene ke bajaye, kist me pehle se tax bharna — 10,000 se zyada tax bane to zaroori." },
  { t: "GST & Tax", q: "Old aur New tax regime me farq?", a: "Old me chhoot (80C, HRA) milti hai par dar zyada. New me chhoot kam par dar kam. Jo kam tax banaye wahi chunein." },
  { t: "GST & Tax", q: "Section 80C me kya aata hai?", a: "LIC, PPF, ELSS, bachhon ki fees, home loan ka principal — Old regime me 1.5 lakh tak ki chhoot." },
  { t: "GST & Tax", q: "Ek GST accountant ka roz ka kaam kya hota hai?", a: "Bill entry, purchase-sale ka milaan, GSTR-2B se ITC check karna, aur samay par return bharna." },

  /* ---------------- Interview / HR (45) ---------------- */
  { t: "Interview / HR", q: "Apne baare me bataiye.", a: "Naam, kahan se hain, kya padha, kaunsa course kiya aur usme kya banaya — 30-40 second me. Personal kahani nahi, kaam ki baat." },
  { t: "Interview / HR", q: "Aapki strength kya hai?", a: "Ek khoobi bataiye aur uska ek asli udaharan dijiye — 'main data me galti nahi karta, isliye course me mere saare assignment bina error ke the'." },
  { t: "Interview / HR", q: "Aapki weakness kya hai?", a: "Asli kami bataiye jispar aap kaam kar rahe hain — 'English bolne me jhijhak thi, isliye roz practice karta hoon'. Jhoothi 'main bahut mehnat karta hoon' na kahein." },
  { t: "Interview / HR", q: "Aap hamare yahan kyun kaam karna chahte hain?", a: "Company ke baare me ek-do baat bataiye jo aapko achhi lagi, aur wo apne kaam se jodiye. Isliye interview se pehle unke baare me padh kar jaayein." },
  { t: "Interview / HR", q: "Hum aapko kyun rakhein?", a: "Jo unhe chahiye aur jo aap kar sakte hain, dono ko milaiye — 'aapko Tally aur GST ka kaam chahiye, maine 3 mahine practical training li hai'." },
  { t: "Interview / HR", q: "Salary kitni chahiye?", a: "'Is pad ke liye jo aapki company ka standard ho' kehna surakshit hai. Number poochha jaye to bazaar ki range bataiye, ek fix aankda nahi." },
  { t: "Interview / HR", q: "5 saal baad khud ko kahan dekhte hain?", a: "Isi kaam me aage badhe hue — 'account assistant se senior accountant banna chahta hoon'. 'Apna business kholunga' kehna is jagah theek nahi." },
  { t: "Interview / HR", q: "Aapko koi anubhav nahi hai, fir kyun rakhein?", a: "Anubhav ki kami maan lijiye, par apna practical kaam dikhaiye — course ke project, assignments, typing speed. Seekhne ki tezi par zor dijiye." },
  { t: "Interview / HR", q: "Kya aap overtime kar sakte hain?", a: "Imaandaari se bataiye. Kar sakte hain to 'zarurat padne par bilkul'. Nahi kar sakte to wajah ke saath saaf mana kar dein — jhooth baad me dikkat karta hai." },
  { t: "Interview / HR", q: "Aapko computer ki kitni jaankari hai?", a: "Sirf 'achhi jaankari hai' na kahein — bataiye kya-kya: 'Word me mail merge, Excel me VLOOKUP aur pivot, Tally me GST entry'." },
  { t: "Interview / HR", q: "Aapki typing speed kya hai?", a: "Asli number bataiye — 'English 35 WPM, Hindi 25 WPM'. Badha kar mat bataiye, wahin test ho sakta hai." },
  { t: "Interview / HR", q: "Kya aap dabav me kaam kar sakte hain?", a: "Haan kehkar ek udaharan dijiye — 'month end par 3 din me 500 bill entry kiye the'." },
  { t: "Interview / HR", q: "Aapne pichhli naukri kyun chhodi?", a: "Purane employer ki burai kabhi na karein. 'Aage seekhne ka mauka chahiye tha' jaisa sakaratmak kaaran dein." },
  { t: "Interview / HR", q: "Aap team me kaam kar sakte hain?", a: "Haan, aur ek udaharan dijiye jahan aapne kisi ki madad ki ya milkar kaam poora kiya." },
  { t: "Interview / HR", q: "Aapse koi badi galti hui ho to bataiye.", a: "Ek asli galti maaniye, aur zyada zor is par dijiye ki aapne use kaise theek kiya aur usse kya seekha." },
  { t: "Interview / HR", q: "Aapko koi sawaal poochhna hai?", a: "Hamesha kuch poochhiye — 'is pad me roz ka kaam kya rahega?' ya 'yahan seekhne ke kya mauke hain?'. 'Kuch nahi' kehna bura lagta hai." },
  { t: "Interview / HR", q: "Interview me kab pahunchna chahiye?", a: "10-15 minute pehle. Der se pahunchna aksar wahin baat khatam kar deta hai." },
  { t: "Interview / HR", q: "Interview me kya pehen kar jaayein?", a: "Saaf, istri kiya hua, saada kapda. Formal shirt aur pant sabse surakshit — chamakdaar rang aur zyada perfume se bachein." },
  { t: "Interview / HR", q: "Interview me kaun se kagaz le jaayein?", a: "Resume ki 2-3 copy, marksheet, certificate, Aadhaar aur passport photo — ek saaf file me." },
  { t: "Interview / HR", q: "Resume kitne page ka hona chahiye?", a: "Fresher ke liye ek page. Do page tabhi jab asli anubhav ho." },
  { t: "Interview / HR", q: "Resume me kya nahi likhna chahiye?", a: "Jhoothi skill, salary ki maang, aur bekaar ki niji jaankari. Jo likha hai uspar sawaal aa sakta hai." },
  { t: "Interview / HR", q: "Body language me kya dhyan rakhein?", a: "Seedha baithein, aankhon me dekh kar baat karein, haath sthir rakhein, aur halka muskurayein." },
  { t: "Interview / HR", q: "Sawaal samajh na aaye to?", a: "Vinamrata se dobara poochh lein — 'kya main sahi samjha ki aap ye poochh rahe hain?'. Andaaza laga kar galat jawab dena bura hai." },
  { t: "Interview / HR", q: "Jawab na pata ho to kya karein?", a: "Saaf kahein 'ye mujhe abhi nahi pata, par main seekh lunga'. Bana kar bolna turant pakda jaata hai." },
  { t: "Interview / HR", q: "Interview ke baad kya karna chahiye?", a: "Dhanyavaad kahein. Ho sake to ek chhota thank-you message ya mail bhejein — bahut kam log karte hain, isliye yaad rehta hai." },
  { t: "Interview / HR", q: "Fresher ke liye sabse bada faayda kya hai?", a: "Practical kaam jo dikha sakein — course ke project, banayi hui Excel sheet, Tally ki company. Sirf certificate se kaam nahi banta." },
  { t: "Interview / HR", q: "Data entry operator se kya ummeed ki jaati hai?", a: "Tez aur bilkul sahi typing, dhyan se kaam, aur diye gaye format ka palan." },
  { t: "Interview / HR", q: "Computer operator ka roz ka kaam kya hota hai?", a: "Data entry, letter aur report banana, print aur scan, file rakhna, aur backup." },
  { t: "Interview / HR", q: "Aap kaam me galti kaise rokte hain?", a: "Entry ke baad ek baar milaan, formula ka natija haath se check, aur zaroori file ka backup." },
  { t: "Interview / HR", q: "Office me confidential data ka kya dhyan rakhenge?", a: "Kisi ko share nahi karunga, computer lock karke uthunga, aur pen drive me bina ijaazat data nahi le jaunga." },
  { t: "Interview / HR", q: "Boss ki baat samajh na aaye to?", a: "Wahin poochh lena chahiye. Adhoora samajh kar kiya gaya kaam dobara karna padta hai." },
  { t: "Interview / HR", q: "Do kaam ek saath mile to kya karenge?", a: "Boss se poochhunga kaunsa pehle chahiye. Khud se tay karne se galat cheez pehle ho sakti hai." },
  { t: "Interview / HR", q: "Aapki sabse badi upalabdhi kya hai?", a: "Koi bhi asli cheez — course pass karna, typing speed badhana, ghar ka kharcha sambhalna. Chhoti par sacchi baat kaafi hai." },
  { t: "Interview / HR", q: "Aap naya kaam kaise seekhte hain?", a: "Pehle dekh kar samajhta hoon, fir khud karke dekhta hoon, aur note bana leta hoon taaki dobara poochhna na pade." },
  { t: "Interview / HR", q: "English theek nahi hai, ye batana chahiye?", a: "Haan, imaandaari se — 'padh-likh leta hoon, bolne ki practice kar raha hoon'. Chhupane se baad me dikkat hoti hai." },
  { t: "Interview / HR", q: "Interview me ghabrahat kaise kam karein?", a: "Pehle se jawab bol kar practice karein, gehri saans lein, aur yaad rakhein ki saamne wala bhi ek insaan hai." },
  { t: "Interview / HR", q: "Joining kab kar sakte hain?", a: "Asli tareekh bataiye. Turant kar sakte hain to ye aapke haq me jaata hai." },
  { t: "Interview / HR", q: "Kya aap doosre sheher ja sakte hain?", a: "Soch kar jawab dein. Haan kehkar baad me mana karna aapka naam kharab karta hai." },
  { t: "Interview / HR", q: "Aapse koi seniority me chhota galti kare to?", a: "Akele me batayunga, sabke saamne nahi. Maqsad kaam theek karana hai, sharminda karna nahi." },
  { t: "Interview / HR", q: "Company me pehle din kya karenge?", a: "Log aur kaam ka tareeka samajhunga, notes banaunga, aur jo bataya jaye wo dhyan se karunga." },
  { t: "Interview / HR", q: "Aapke liye achhi naukri kya hai?", a: "Jahan kaam seekhne ko mile, mehnat ki kadar ho, aur aage badhne ka raasta ho." },
  { t: "Interview / HR", q: "Salary kam mile to karenge?", a: "Shuruaat me seekhne ko zyada mahatva dunga, par apni zaroorat bhi saaf rakhunga. Poori tarah jhukna bhi theek nahi." },
  { t: "Interview / HR", q: "Aap khud ko kaise motivate karte hain?", a: "Chhote lakshya banata hoon aur poora hone par aage badhta hoon. Kaam poora hone ki santushti hi sabse badi prerna hai." },
  { t: "Interview / HR", q: "Aapko criticism kaisa lagta hai?", a: "Agar wo kaam ke baare me hai to accha lagta hai — usse hi sudhaar hota hai. Main use niji roop se nahi leta." },
  { t: "Interview / HR", q: "Interview me sabse zaroori baat kya hai?", a: "Sach bolna. Jo aata hai wo saaf bataiye, jo nahi aata wo maan lijiye. Jhooth se mili naukri jyada din nahi tikti." }
];
