/* ==========================================================================
   Soft Skill Zone — Journal Entry ka bank (Dr / Cr practice)
   --------------------------------------------------------------------------
   Accounting me sabse pehli aur sabse zaroori aadat yahi hai: kaunsa khaata
   Debit hoga aur kaunsa Credit. Baaki sab — ledger, trial balance, final
   accounts — isi ek aadat par khada hai. Jise ye pakka aa gaya, uska aage
   ka poora course aasaan ho jaata hai.

   YAHAN "KYUN" HAR SAWAAL KE SAATH LIKHA NAHI HAI — BANAYA JAATA HAI

   Har entry ke saath alag-alag samjhaav likhne ka matlab hota 500 alag-alag
   line, jinme se koi na koi galat ya doosri se ulti reh jaati. Iske bajaye
   har khaate ka SWABHAV (Asset, Expense, Liability, Capital, Income) yahan
   ek baar likha hai, aur samjhaav usi se banta hai.

   Faayda sirf mehnat bachne ka nahi hai. Student ko har baar wahi ek niyam
   dohra kar milta hai — "Asset badha to Debit", "Kharcha hamesha Debit" —
   aur ratne ke bajaye niyam baith jaata hai. Naya sawaal jodna bhi seedha
   ho gaya: bas transaction, Dr aur Cr likhiye; samjhaav apne aap ban jaata
   hai aur baaki sab se mel khaata hai.

   HISAAB KA TARIKA — AAJKAL WALA (modern rules)

     Asset      badhe   → Debit    ghate → Credit
     Expense    hamesha → Debit
     Liability  badhe   → Credit   ghate → Debit
     Capital    badhe   → Credit   ghate → Debit  (drawings)
     Income     hamesha → Credit

   Kuchh khaate is saanche me theek nahi baithte — Purchase Return, Sales
   Return, Drawings. Unke liye `note` likh diya gaya hai, jo bane-banaye
   samjhaav ki jagah le leta hai.

   RAKAM AUR NAAM BADALTE HAIN, NIYAM NAHI

   Ek hi tarah ki entry kai roop me aati hai — alag customer, alag rakam,
   alag maal. Ye jaanbujh kar hai: student ko "Ram Traders wala sawaal"
   yaad nahi karna, "udhaar kharida to Purchases Dr" pehchanna hai. Isliye
   naam dekh kar jawab dene ki aadat yahan chalti nahi.
   ========================================================================== */

/** Khaata → uska swabhav. Yahi se Dr/Cr ka samjhaav banta hai. */
export const ACCOUNTS = Object.freeze({

  /* ---- Asset ---- */
  "Cash A/c":               { type: "asset" },
  "Bank A/c":               { type: "asset" },
  "Furniture A/c":          { type: "asset" },
  "Machinery A/c":          { type: "asset" },
  "Computer A/c":           { type: "asset" },
  "Building A/c":           { type: "asset" },
  "Land A/c":               { type: "asset" },
  "Vehicle A/c":            { type: "asset" },
  "Generator A/c":          { type: "asset" },
  "Air Conditioner A/c":    { type: "asset" },
  "Tools A/c":              { type: "asset" },
  "Prepaid Insurance A/c":  { type: "asset" },
  "Prepaid Rent A/c":       { type: "asset" },
  "Accrued Commission A/c": { type: "asset" },
  "Input CGST A/c":         { type: "asset" },
  "Input SGST A/c":         { type: "asset" },
  "Input IGST A/c":         { type: "asset" },

  /* Udhaar bechne par jo customer paisa dega — wo hamara Asset hai */
  "Suresh":            { type: "asset",  who: "customer" },
  "Anita Devi":        { type: "asset",  who: "customer" },
  "Verma Stores":      { type: "asset",  who: "customer" },
  "Rajesh Kumar":      { type: "asset",  who: "customer" },
  "Sharma Brothers":   { type: "asset",  who: "customer" },
  "Priya Enterprises": { type: "asset",  who: "customer" },
  "Mohan Lal":         { type: "asset",  who: "customer" },
  "Bharti Traders":    { type: "asset",  who: "customer" },

  /* ---- Liability ---- */
  /* Udhaar kharidne par jise hume dena hai — wo hamari Liability hai */
  "Ram Traders":         { type: "liability", who: "supplier" },
  "Gupta & Co.":         { type: "liability", who: "supplier" },
  "Singh Agencies":      { type: "liability", who: "supplier" },
  "Kumar Sons":          { type: "liability", who: "supplier" },
  "Nirmal Distributors": { type: "liability", who: "supplier" },
  "Yadav Enterprises":   { type: "liability", who: "supplier" },

  "Bank Loan A/c":               { type: "liability" },
  "Outstanding Salary A/c":      { type: "liability" },
  "Outstanding Rent A/c":        { type: "liability" },
  "Outstanding Wages A/c":       { type: "liability" },
  "Outstanding Electricity A/c": { type: "liability" },
  "Output CGST A/c":             { type: "liability" },
  "Output SGST A/c":             { type: "liability" },
  "Output IGST A/c":             { type: "liability" },

  /* ---- Capital ---- */
  "Capital A/c":            { type: "capital" },
  "Drawings A/c":           { type: "capital",
    note: "Drawings maalik ka apna nikala hua paisa hai — isse Capital ghatta hai, aur Capital ghate to Debit." },

  /* ---- Expense ---- */
  "Purchases A/c":             { type: "expense" },
  "Salary A/c":                { type: "expense" },
  "Wages A/c":                 { type: "expense" },
  "Rent A/c":                  { type: "expense" },
  "Electricity A/c":           { type: "expense" },
  "Telephone A/c":             { type: "expense" },
  "Advertisement A/c":         { type: "expense" },
  "Carriage A/c":              { type: "expense" },
  "Insurance A/c":             { type: "expense" },
  "Repairs A/c":               { type: "expense" },
  "Printing & Stationery A/c": { type: "expense" },
  "Discount Allowed A/c":      { type: "expense" },
  "Bad Debts A/c":             { type: "expense" },
  "Depreciation A/c":          { type: "expense" },
  "Interest A/c":              { type: "expense" },
  "Commission A/c":            { type: "expense" },
  "Bank Charges A/c":          { type: "expense" },
  "Postage A/c":               { type: "expense" },
  "Travelling A/c":            { type: "expense" },
  "Petrol A/c":                { type: "expense" },
  "Packing A/c":               { type: "expense" },
  "Legal Fees A/c":            { type: "expense" },
  "Audit Fees A/c":            { type: "expense" },
  "Office Expenses A/c":       { type: "expense" },
  "Staff Welfare A/c":         { type: "expense" },
  "Donation A/c":              { type: "expense" },
  "Freight A/c":               { type: "expense" },
  "Sales Return A/c":       { type: "expense",
    note: "Sales Return se hamari Sales ghatti hai. Income ghate to Debit — isliye ye Debit hota hai." },

  /* ---- Income ---- */
  "Sales A/c":               { type: "income" },
  "Discount Received A/c":   { type: "income" },
  "Commission Received A/c": { type: "income" },
  "Interest Received A/c":   { type: "income" },
  "Rent Received A/c":       { type: "income" },
  "Purchase Return A/c":    { type: "income",
    note: "Purchase Return se hamara kharcha ghatta hai. Kharcha ghate to Credit — isliye ye Credit hota hai." }
});

/** Chapter ke naam — jaise course me padhaye jaate hain. */
export const CHAPTERS = Object.freeze([
  { id: "basic",  label: "Shuruaat — Cash, Capital, Maal" },
  { id: "credit", label: "Udhaar — Customer aur Supplier" },
  { id: "bank",   label: "Bank, Cheque aur Loan" },
  { id: "gst",    label: "GST wali entry" },
  { id: "exp",    label: "Kharche aur Aamdani" },
  { id: "asset",  label: "Asset kharidna, bechna, Depreciation" },
  { id: "adjust", label: "Adjustment — Outstanding, Prepaid, Bad Debts" },
  { id: "retdis", label: "Return, Discount aur Drawings" }
]);

/**
 * Har entry: ch = chapter, q = transaction, dr / cr = sahi jawab.
 *
 * Rakam gol number me hai — dhyan Dr/Cr par rahe, jodne par nahi. GST wali
 * entry me sirf tax wala hissa poochha jaata hai, poori entry nahi, taaki
 * Input/Output ka farak saaf ho jaaye.
 */
export const JOURNAL = Object.freeze([

  /* ---------------- Shuruaat — Cash, Capital, Maal (76) ---------------- */
  { ch: "basic", q: "Business shuru kiya — apne paas se ₹1,50,000 cash lagaya.", dr: "Cash A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Business me ₹25,000 aur cash lagaya.", dr: "Cash A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Maalik ne ₹50,000 apne bank khaate se business ke bank khaate me daale.", dr: "Bank A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Business shuru karte waqt ₹75,000 ka furniture apne ghar se laga diya.", dr: "Furniture A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Maalik ne apni ₹3,00,000 ki machinery business me laga di.", dr: "Machinery A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Maalik ne apna ₹1,20,000 ka computer business me laga diya.", dr: "Computer A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Business shuru kiya — apne paas se ₹6,00,000 cash lagaya.", dr: "Cash A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Business me ₹40,000 aur cash lagaya.", dr: "Cash A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Maalik ne ₹65,000 apne bank khaate se business ke bank khaate me daale.", dr: "Bank A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Business shuru karte waqt ₹1,00,000 ka furniture apne ghar se laga diya.", dr: "Furniture A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Maalik ne apni ₹2,25,000 ki machinery business me laga di.", dr: "Machinery A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Maalik ne apna ₹30,000 ka computer business me laga diya.", dr: "Computer A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Business shuru kiya — apne paas se ₹4,50,000 cash lagaya.", dr: "Cash A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Business me ₹55,000 aur cash lagaya.", dr: "Cash A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Maalik ne ₹80,000 apne bank khaate se business ke bank khaate me daale.", dr: "Bank A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Business shuru karte waqt ₹1,25,000 ka furniture apne ghar se laga diya.", dr: "Furniture A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Maalik ne apni ₹1,75,000 ki machinery business me laga di.", dr: "Machinery A/c", cr: "Capital A/c" },
  { ch: "basic", q: "Maalik ne apna ₹45,000 ka computer business me laga diya.", dr: "Computer A/c", cr: "Capital A/c" },
  { ch: "basic", q: "₹70,000 ka maal (kapde) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹1,10,000 ka maal (mobile) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹35,000 ka maal (juta-chappal) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹60,000 ka maal (stationery) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹90,000 ka maal (bartan) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹25,000 ka maal (grocery) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹50,000 ka maal (electronics) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹75,000 ka maal (hardware) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹1,20,000 ka maal (dawai) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹40,000 ka maal (khilone) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹65,000 ka maal (book) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹1,00,000 ka maal (cosmetic) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹30,000 ka maal (kapde) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹55,000 ka maal (mobile) cash dekar kharida.", dr: "Purchases A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹6,000 ka maal (grocery) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹12,000 ka maal (electronics) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹20,000 ka maal (hardware) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹32,000 ka maal (dawai) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹11,000 ka maal (khilone) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹18,000 ka maal (book) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹30,000 ka maal (cosmetic) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹10,000 ka maal (kapde) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹16,000 ka maal (mobile) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹28,000 ka maal (juta-chappal) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹9,000 ka maal (stationery) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹15,000 ka maal (bartan) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹25,000 ka maal (grocery) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "₹8,500 ka maal (electronics) cash me becha.", dr: "Cash A/c", cr: "Sales A/c" },
  { ch: "basic", q: "Dukaan ka kiraya ₹14,000 cash diya.", dr: "Rent A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Staff ki salary ₹24,000 cash di.", dr: "Salary A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Mazdoori (wages) ₹1,200 cash di.", dr: "Wages A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Bijli ka bill ₹3,000 cash me diya.", dr: "Electricity A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Telephone aur internet ka ₹150 ka bill cash me diya.", dr: "Telephone A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Akhbaar me vigyapan ka ₹6,000 cash diya.", dr: "Advertisement A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Printing aur stationery par ₹400 cash kharch hua.", dr: "Printing & Stationery A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Maal laane ka bhada (carriage) ₹750 cash diya.", dr: "Carriage A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Marammat par ₹1,800 cash kharch hua.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Dukaan ka kiraya ₹7,500 cash diya.", dr: "Rent A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Staff ki salary ₹12,500 cash di.", dr: "Salary A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Mazdoori (wages) ₹3,500 cash di.", dr: "Wages A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Bijli ka bill ₹7,000 cash me diya.", dr: "Electricity A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Telephone aur internet ka ₹1,200 ka bill cash me diya.", dr: "Telephone A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Akhbaar me vigyapan ka ₹2,200 cash diya.", dr: "Advertisement A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Printing aur stationery par ₹200 cash kharch hua.", dr: "Printing & Stationery A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Maal laane ka bhada (carriage) ₹450 cash diya.", dr: "Carriage A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Marammat par ₹4,500 cash kharch hua.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Dukaan ke liye ₹80,000 ka furniture cash dekar kharida.", dr: "Furniture A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Ek computer ₹1,25,000 cash dekar kharida.", dr: "Computer A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹3,50,000 ki machine cash dekar kharidi.", dr: "Machinery A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Kaam ke auzaar (tools) ₹22,000 cash me kharide.", dr: "Tools A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Dukaan ke liye AC ₹45,000 cash dekar lagwaya.", dr: "Air Conditioner A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹70,000 ka generator cash dekar kharida.", dr: "Generator A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Dukaan ke liye ₹1,10,000 ka furniture cash dekar kharida.", dr: "Furniture A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Ek computer ₹35,000 cash dekar kharida.", dr: "Computer A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹7,50,000 ki machine cash dekar kharidi.", dr: "Machinery A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Kaam ke auzaar (tools) ₹6,000 cash me kharide.", dr: "Tools A/c", cr: "Cash A/c" },
  { ch: "basic", q: "Dukaan ke liye AC ₹60,000 cash dekar lagwaya.", dr: "Air Conditioner A/c", cr: "Cash A/c" },
  { ch: "basic", q: "₹90,000 ka generator cash dekar kharida.", dr: "Generator A/c", cr: "Cash A/c" },

  /* ---------------- Udhaar — Customer aur Supplier (70) ---------------- */
  { ch: "credit", q: "Ram Traders se ₹25,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Ram Traders" },
  { ch: "credit", q: "Gupta & Co. se ₹50,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Gupta & Co." },
  { ch: "credit", q: "Singh Agencies se ₹75,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Singh Agencies" },
  { ch: "credit", q: "Kumar Sons se ₹1,20,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Kumar Sons" },
  { ch: "credit", q: "Nirmal Distributors se ₹40,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Nirmal Distributors" },
  { ch: "credit", q: "Yadav Enterprises se ₹65,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Yadav Enterprises" },
  { ch: "credit", q: "Ram Traders se ₹1,00,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Ram Traders" },
  { ch: "credit", q: "Gupta & Co. se ₹30,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Gupta & Co." },
  { ch: "credit", q: "Singh Agencies se ₹55,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Singh Agencies" },
  { ch: "credit", q: "Kumar Sons se ₹80,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Kumar Sons" },
  { ch: "credit", q: "Nirmal Distributors se ₹1,25,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Nirmal Distributors" },
  { ch: "credit", q: "Yadav Enterprises se ₹45,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Yadav Enterprises" },
  { ch: "credit", q: "Ram Traders se ₹70,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Ram Traders" },
  { ch: "credit", q: "Gupta & Co. se ₹1,10,000 ka maal udhaar kharida.", dr: "Purchases A/c", cr: "Gupta & Co." },
  { ch: "credit", q: "Suresh ko ₹12,000 ka maal udhaar becha.", dr: "Suresh", cr: "Sales A/c" },
  { ch: "credit", q: "Anita Devi ko ₹20,000 ka maal udhaar becha.", dr: "Anita Devi", cr: "Sales A/c" },
  { ch: "credit", q: "Verma Stores ko ₹32,000 ka maal udhaar becha.", dr: "Verma Stores", cr: "Sales A/c" },
  { ch: "credit", q: "Rajesh Kumar ko ₹11,000 ka maal udhaar becha.", dr: "Rajesh Kumar", cr: "Sales A/c" },
  { ch: "credit", q: "Sharma Brothers ko ₹18,000 ka maal udhaar becha.", dr: "Sharma Brothers", cr: "Sales A/c" },
  { ch: "credit", q: "Priya Enterprises ko ₹30,000 ka maal udhaar becha.", dr: "Priya Enterprises", cr: "Sales A/c" },
  { ch: "credit", q: "Mohan Lal ko ₹10,000 ka maal udhaar becha.", dr: "Mohan Lal", cr: "Sales A/c" },
  { ch: "credit", q: "Bharti Traders ko ₹16,000 ka maal udhaar becha.", dr: "Bharti Traders", cr: "Sales A/c" },
  { ch: "credit", q: "Suresh ko ₹28,000 ka maal udhaar becha.", dr: "Suresh", cr: "Sales A/c" },
  { ch: "credit", q: "Anita Devi ko ₹9,000 ka maal udhaar becha.", dr: "Anita Devi", cr: "Sales A/c" },
  { ch: "credit", q: "Verma Stores ko ₹15,000 ka maal udhaar becha.", dr: "Verma Stores", cr: "Sales A/c" },
  { ch: "credit", q: "Rajesh Kumar ko ₹25,000 ka maal udhaar becha.", dr: "Rajesh Kumar", cr: "Sales A/c" },
  { ch: "credit", q: "Sharma Brothers ko ₹8,500 ka maal udhaar becha.", dr: "Sharma Brothers", cr: "Sales A/c" },
  { ch: "credit", q: "Priya Enterprises ko ₹14,000 ka maal udhaar becha.", dr: "Priya Enterprises", cr: "Sales A/c" },
  { ch: "credit", q: "Ram Traders ko ₹35,000 cash chuka diya.", dr: "Ram Traders", cr: "Cash A/c" },
  { ch: "credit", q: "Gupta & Co. ko ₹60,000 cash chuka diya.", dr: "Gupta & Co.", cr: "Cash A/c" },
  { ch: "credit", q: "Singh Agencies ko ₹90,000 cash chuka diya.", dr: "Singh Agencies", cr: "Cash A/c" },
  { ch: "credit", q: "Kumar Sons ko ₹25,000 cash chuka diya.", dr: "Kumar Sons", cr: "Cash A/c" },
  { ch: "credit", q: "Nirmal Distributors ko ₹50,000 cash chuka diya.", dr: "Nirmal Distributors", cr: "Cash A/c" },
  { ch: "credit", q: "Yadav Enterprises ko ₹75,000 cash chuka diya.", dr: "Yadav Enterprises", cr: "Cash A/c" },
  { ch: "credit", q: "Ram Traders ko ₹1,20,000 cash chuka diya.", dr: "Ram Traders", cr: "Cash A/c" },
  { ch: "credit", q: "Gupta & Co. ko ₹40,000 cash chuka diya.", dr: "Gupta & Co.", cr: "Cash A/c" },
  { ch: "credit", q: "Singh Agencies ko ₹65,000 cash chuka diya.", dr: "Singh Agencies", cr: "Cash A/c" },
  { ch: "credit", q: "Kumar Sons ko ₹1,00,000 cash chuka diya.", dr: "Kumar Sons", cr: "Cash A/c" },
  { ch: "credit", q: "Suresh se ₹24,000 cash mila.", dr: "Cash A/c", cr: "Suresh" },
  { ch: "credit", q: "Anita Devi se ₹7,500 cash mila.", dr: "Cash A/c", cr: "Anita Devi" },
  { ch: "credit", q: "Verma Stores se ₹12,500 cash mila.", dr: "Cash A/c", cr: "Verma Stores" },
  { ch: "credit", q: "Rajesh Kumar se ₹22,000 cash mila.", dr: "Cash A/c", cr: "Rajesh Kumar" },
  { ch: "credit", q: "Sharma Brothers se ₹6,000 cash mila.", dr: "Cash A/c", cr: "Sharma Brothers" },
  { ch: "credit", q: "Priya Enterprises se ₹12,000 cash mila.", dr: "Cash A/c", cr: "Priya Enterprises" },
  { ch: "credit", q: "Mohan Lal se ₹20,000 cash mila.", dr: "Cash A/c", cr: "Mohan Lal" },
  { ch: "credit", q: "Bharti Traders se ₹32,000 cash mila.", dr: "Cash A/c", cr: "Bharti Traders" },
  { ch: "credit", q: "Suresh se ₹11,000 cash mila.", dr: "Cash A/c", cr: "Suresh" },
  { ch: "credit", q: "Anita Devi se ₹18,000 cash mila.", dr: "Cash A/c", cr: "Anita Devi" },
  { ch: "credit", q: "Verma Stores se ₹30,000 ka cheque mila, bank me jama kar diya.", dr: "Bank A/c", cr: "Verma Stores" },
  { ch: "credit", q: "Rajesh Kumar se ₹55,000 ka cheque mila, bank me jama kar diya.", dr: "Bank A/c", cr: "Rajesh Kumar" },
  { ch: "credit", q: "Sharma Brothers se ₹80,000 ka cheque mila, bank me jama kar diya.", dr: "Bank A/c", cr: "Sharma Brothers" },
  { ch: "credit", q: "Priya Enterprises se ₹1,25,000 ka cheque mila, bank me jama kar diya.", dr: "Bank A/c", cr: "Priya Enterprises" },
  { ch: "credit", q: "Mohan Lal se ₹45,000 ka cheque mila, bank me jama kar diya.", dr: "Bank A/c", cr: "Mohan Lal" },
  { ch: "credit", q: "Bharti Traders se ₹70,000 ka cheque mila, bank me jama kar diya.", dr: "Bank A/c", cr: "Bharti Traders" },
  { ch: "credit", q: "Suresh se ₹1,10,000 ka cheque mila, bank me jama kar diya.", dr: "Bank A/c", cr: "Suresh" },
  { ch: "credit", q: "Anita Devi se ₹35,000 ka cheque mila, bank me jama kar diya.", dr: "Bank A/c", cr: "Anita Devi" },
  { ch: "credit", q: "Gupta & Co. ko ₹60,000 ka cheque diya.", dr: "Gupta & Co.", cr: "Bank A/c" },
  { ch: "credit", q: "Singh Agencies ko ₹90,000 ka cheque diya.", dr: "Singh Agencies", cr: "Bank A/c" },
  { ch: "credit", q: "Kumar Sons ko ₹25,000 ka cheque diya.", dr: "Kumar Sons", cr: "Bank A/c" },
  { ch: "credit", q: "Nirmal Distributors ko ₹50,000 ka cheque diya.", dr: "Nirmal Distributors", cr: "Bank A/c" },
  { ch: "credit", q: "Yadav Enterprises ko ₹75,000 ka cheque diya.", dr: "Yadav Enterprises", cr: "Bank A/c" },
  { ch: "credit", q: "Ram Traders ko ₹1,20,000 ka cheque diya.", dr: "Ram Traders", cr: "Bank A/c" },
  { ch: "credit", q: "Gupta & Co. ko ₹40,000 ka cheque diya.", dr: "Gupta & Co.", cr: "Bank A/c" },
  { ch: "credit", q: "Singh Agencies ko ₹65,000 ka cheque diya.", dr: "Singh Agencies", cr: "Bank A/c" },
  { ch: "credit", q: "Kumar Sons se ₹1,00,000 ka furniture udhaar kharida.", dr: "Furniture A/c", cr: "Kumar Sons" },
  { ch: "credit", q: "Nirmal Distributors se ₹30,000 ka furniture udhaar kharida.", dr: "Furniture A/c", cr: "Nirmal Distributors" },
  { ch: "credit", q: "Yadav Enterprises se ₹55,000 ka furniture udhaar kharida.", dr: "Furniture A/c", cr: "Yadav Enterprises" },
  { ch: "credit", q: "Ram Traders se ₹80,000 ka furniture udhaar kharida.", dr: "Furniture A/c", cr: "Ram Traders" },
  { ch: "credit", q: "Gupta & Co. se ₹1,25,000 ka furniture udhaar kharida.", dr: "Furniture A/c", cr: "Gupta & Co." },
  { ch: "credit", q: "Singh Agencies se ₹45,000 ka furniture udhaar kharida.", dr: "Furniture A/c", cr: "Singh Agencies" },

  /* ---------------- Bank, Cheque aur Loan (56) ---------------- */
  { ch: "bank", q: "Bank me ₹70,000 cash jama kiya.", dr: "Bank A/c", cr: "Cash A/c" },
  { ch: "bank", q: "Bank se ₹30,000 cash nikala.", dr: "Cash A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bank se ₹2,50,000 ka loan liya, paisa bank khaate me aaya.", dr: "Bank A/c", cr: "Bank Loan A/c" },
  { ch: "bank", q: "Bank loan ki kist ₹10,000 bank se chukayi.", dr: "Bank Loan A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bank ne khaate par ₹8,000 byaaj diya.", dr: "Bank A/c", cr: "Interest Received A/c" },
  { ch: "bank", q: "Bank ne ₹800 ka service charge kaata.", dr: "Bank Charges A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Loan par ₹2,800 byaaj bank se diya.", dr: "Interest A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Dukaan ka kiraya ₹16,000 cheque se diya.", dr: "Rent A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Staff ki salary ₹28,000 bank se transfer ki.", dr: "Salary A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bijli ka bill ₹5,500 online bank se bhara.", dr: "Electricity A/c", cr: "Bank A/c" },
  { ch: "bank", q: "₹1,10,000 ka maal cheque dekar kharida.", dr: "Purchases A/c", cr: "Bank A/c" },
  { ch: "bank", q: "₹35,000 ka maal becha, paisa seedha bank khaate me aaya.", dr: "Bank A/c", cr: "Sales A/c" },
  { ch: "bank", q: "Business me ₹5,00,000 aur lagaya, paisa bank khaate me daala.", dr: "Bank A/c", cr: "Capital A/c" },
  { ch: "bank", q: "Bima (insurance) ka ₹1,500 premium bank se bhara.", dr: "Insurance A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Cheque bounce hone par bank ne ₹1,500 charge kaata.", dr: "Bank Charges A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bank ne fixed deposit ka ₹3,200 byaaj khaate me daala.", dr: "Bank A/c", cr: "Interest Received A/c" },
  { ch: "bank", q: "Vigyapan ka ₹6,500 bill online bank se chukaya.", dr: "Advertisement A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Loan ka poora ₹2,00,000 bank se ek saath chuka diya.", dr: "Bank Loan A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Dukaan ke liye ₹60,000 ka maal kharida, paisa bank se gaya.", dr: "Purchases A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Telephone ka ₹250 bill bank se auto-debit hua.", dr: "Telephone A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Godown ka kiraya ₹9,000 bank se transfer kiya.", dr: "Rent A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bank se ₹4,00,000 ka naya loan liya.", dr: "Bank A/c", cr: "Bank Loan A/c" },
  { ch: "bank", q: "ATM se business ke liye ₹15,000 cash nikala.", dr: "Cash A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Din bhar ki bikri ka ₹25,000 cash bank me jama kiya.", dr: "Bank A/c", cr: "Cash A/c" },
  { ch: "bank", q: "Bank me ₹90,000 cash jama kiya.", dr: "Bank A/c", cr: "Cash A/c" },
  { ch: "bank", q: "Bank se ₹8,500 cash nikala.", dr: "Cash A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bank se ₹1,50,000 ka loan liya, paisa bank khaate me aaya.", dr: "Bank A/c", cr: "Bank Loan A/c" },
  { ch: "bank", q: "Bank loan ki kist ₹14,000 bank se chukayi.", dr: "Bank Loan A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bank ne khaate par ₹2,000 byaaj diya.", dr: "Bank A/c", cr: "Interest Received A/c" },
  { ch: "bank", q: "Bank ne ₹500 ka service charge kaata.", dr: "Bank Charges A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Loan par ₹4,000 byaaj bank se diya.", dr: "Interest A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Dukaan ka kiraya ₹24,000 cheque se diya.", dr: "Rent A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Staff ki salary ₹7,500 bank se transfer ki.", dr: "Salary A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bijli ka bill ₹7,500 online bank se bhara.", dr: "Electricity A/c", cr: "Bank A/c" },
  { ch: "bank", q: "₹25,000 ka maal cheque dekar kharida.", dr: "Purchases A/c", cr: "Bank A/c" },
  { ch: "bank", q: "₹50,000 ka maal becha, paisa seedha bank khaate me aaya.", dr: "Bank A/c", cr: "Sales A/c" },
  { ch: "bank", q: "Business me ₹3,00,000 aur lagaya, paisa bank khaate me daala.", dr: "Bank A/c", cr: "Capital A/c" },
  { ch: "bank", q: "Bima (insurance) ka ₹2,500 premium bank se bhara.", dr: "Insurance A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Cheque bounce hone par bank ne ₹900 charge kaata.", dr: "Bank Charges A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bank ne fixed deposit ka ₹5,000 byaaj khaate me daala.", dr: "Bank A/c", cr: "Interest Received A/c" },
  { ch: "bank", q: "Vigyapan ka ₹1,200 bill online bank se chukaya.", dr: "Advertisement A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Loan ka poora ₹6,00,000 bank se ek saath chuka diya.", dr: "Bank Loan A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Dukaan ke liye ₹75,000 ka maal kharida, paisa bank se gaya.", dr: "Purchases A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Telephone ka ₹1,800 bill bank se auto-debit hua.", dr: "Telephone A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Godown ka kiraya ₹12,500 bank se transfer kiya.", dr: "Rent A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bank se ₹2,25,000 ka naya loan liya.", dr: "Bank A/c", cr: "Bank Loan A/c" },
  { ch: "bank", q: "ATM se business ke liye ₹22,000 cash nikala.", dr: "Cash A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Din bhar ki bikri ka ₹6,000 cash bank me jama kiya.", dr: "Bank A/c", cr: "Cash A/c" },
  { ch: "bank", q: "Bank me ₹1,20,000 cash jama kiya.", dr: "Bank A/c", cr: "Cash A/c" },
  { ch: "bank", q: "Bank se ₹12,000 cash nikala.", dr: "Cash A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bank se ₹4,50,000 ka loan liya, paisa bank khaate me aaya.", dr: "Bank A/c", cr: "Bank Loan A/c" },
  { ch: "bank", q: "Bank loan ki kist ₹20,000 bank se chukayi.", dr: "Bank Loan A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Bank ne khaate par ₹3,000 byaaj diya.", dr: "Bank A/c", cr: "Interest Received A/c" },
  { ch: "bank", q: "Bank ne ₹300 ka service charge kaata.", dr: "Bank Charges A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Loan par ₹6,000 byaaj bank se diya.", dr: "Interest A/c", cr: "Bank A/c" },
  { ch: "bank", q: "Dukaan ka kiraya ₹32,000 cheque se diya.", dr: "Rent A/c", cr: "Bank A/c" },

  /* ---------------- GST wali entry (64) ---------------- */
  { ch: "gst", q: "₹10,000 ka maal cash kharida, CGST 9% — sirf CGST wala hissa.", dr: "Input CGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹10,000 ka maal cash kharida, SGST 9% — sirf SGST wala hissa.", dr: "Input SGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹50,000 ka maal cash kharida, CGST 9% — sirf CGST wala hissa.", dr: "Input CGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹50,000 ka maal cash kharida, SGST 9% — sirf SGST wala hissa.", dr: "Input SGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹45,000 ka maal cash kharida, CGST 9% — sirf CGST wala hissa.", dr: "Input CGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹45,000 ka maal cash kharida, SGST 9% — sirf SGST wala hissa.", dr: "Input SGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹20,000 ka maal cash kharida, CGST 9% — sirf CGST wala hissa.", dr: "Input CGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹20,000 ka maal cash kharida, SGST 9% — sirf SGST wala hissa.", dr: "Input SGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹60,000 ka maal cash kharida, CGST 9% — sirf CGST wala hissa.", dr: "Input CGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹60,000 ka maal cash kharida, SGST 9% — sirf SGST wala hissa.", dr: "Input SGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹75,000 ka maal cash kharida, CGST 9% — sirf CGST wala hissa.", dr: "Input CGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹75,000 ka maal cash kharida, SGST 9% — sirf SGST wala hissa.", dr: "Input SGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "₹25,000 ka maal cash becha, CGST 9% — sirf CGST wala hissa.", dr: "Cash A/c", cr: "Output CGST A/c" },
  { ch: "gst", q: "₹25,000 ka maal cash becha, SGST 9% — sirf SGST wala hissa.", dr: "Cash A/c", cr: "Output SGST A/c" },
  { ch: "gst", q: "₹80,000 ka maal cash becha, CGST 9% — sirf CGST wala hissa.", dr: "Cash A/c", cr: "Output CGST A/c" },
  { ch: "gst", q: "₹80,000 ka maal cash becha, SGST 9% — sirf SGST wala hissa.", dr: "Cash A/c", cr: "Output SGST A/c" },
  { ch: "gst", q: "₹35,000 ka maal cash becha, CGST 9% — sirf CGST wala hissa.", dr: "Cash A/c", cr: "Output CGST A/c" },
  { ch: "gst", q: "₹35,000 ka maal cash becha, SGST 9% — sirf SGST wala hissa.", dr: "Cash A/c", cr: "Output SGST A/c" },
  { ch: "gst", q: "₹30,000 ka maal cash becha, CGST 9% — sirf CGST wala hissa.", dr: "Cash A/c", cr: "Output CGST A/c" },
  { ch: "gst", q: "₹30,000 ka maal cash becha, SGST 9% — sirf SGST wala hissa.", dr: "Cash A/c", cr: "Output SGST A/c" },
  { ch: "gst", q: "₹1,00,000 ka maal cash becha, CGST 9% — sirf CGST wala hissa.", dr: "Cash A/c", cr: "Output CGST A/c" },
  { ch: "gst", q: "₹1,00,000 ka maal cash becha, SGST 9% — sirf SGST wala hissa.", dr: "Cash A/c", cr: "Output SGST A/c" },
  { ch: "gst", q: "₹55,000 ka maal cash becha, CGST 9% — sirf CGST wala hissa.", dr: "Cash A/c", cr: "Output CGST A/c" },
  { ch: "gst", q: "₹55,000 ka maal cash becha, SGST 9% — sirf SGST wala hissa.", dr: "Cash A/c", cr: "Output SGST A/c" },
  { ch: "gst", q: "Doosre rajya se ₹40,000 ka maal kharida, IGST 18% — sirf IGST wala hissa.", dr: "Input IGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "Doosre rajya se ₹15,000 ka maal kharida, IGST 18% — sirf IGST wala hissa.", dr: "Input IGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "Doosre rajya se ₹10,000 ka maal kharida, IGST 18% — sirf IGST wala hissa.", dr: "Input IGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "Doosre rajya se ₹50,000 ka maal kharida, IGST 18% — sirf IGST wala hissa.", dr: "Input IGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "Doosre rajya se ₹45,000 ka maal kharida, IGST 18% — sirf IGST wala hissa.", dr: "Input IGST A/c", cr: "Cash A/c" },
  { ch: "gst", q: "Doosre rajya me Suresh ko ₹20,000 ka maal becha, IGST 18% — sirf IGST wala hissa.", dr: "Suresh", cr: "Output IGST A/c" },
  { ch: "gst", q: "Doosre rajya me Anita Devi ko ₹60,000 ka maal becha, IGST 18% — sirf IGST wala hissa.", dr: "Anita Devi", cr: "Output IGST A/c" },
  { ch: "gst", q: "Doosre rajya me Verma Stores ko ₹75,000 ka maal becha, IGST 18% — sirf IGST wala hissa.", dr: "Verma Stores", cr: "Output IGST A/c" },
  { ch: "gst", q: "Doosre rajya me Rajesh Kumar ko ₹25,000 ka maal becha, IGST 18% — sirf IGST wala hissa.", dr: "Rajesh Kumar", cr: "Output IGST A/c" },
  { ch: "gst", q: "Doosre rajya me Sharma Brothers ko ₹80,000 ka maal becha, IGST 18% — sirf IGST wala hissa.", dr: "Sharma Brothers", cr: "Output IGST A/c" },
  { ch: "gst", q: "Ram Traders se udhaar maal kharida — usi bill ka Input CGST wala hissa (₹35,000 par 9%).", dr: "Input CGST A/c", cr: "Ram Traders" },
  { ch: "gst", q: "Gupta & Co. se udhaar maal kharida — usi bill ka Input CGST wala hissa (₹30,000 par 9%).", dr: "Input CGST A/c", cr: "Gupta & Co." },
  { ch: "gst", q: "Singh Agencies se udhaar maal kharida — usi bill ka Input CGST wala hissa (₹1,00,000 par 9%).", dr: "Input CGST A/c", cr: "Singh Agencies" },
  { ch: "gst", q: "Kumar Sons se udhaar maal kharida — usi bill ka Input CGST wala hissa (₹55,000 par 9%).", dr: "Input CGST A/c", cr: "Kumar Sons" },
  { ch: "gst", q: "Nirmal Distributors se udhaar maal kharida — usi bill ka Input CGST wala hissa (₹40,000 par 9%).", dr: "Input CGST A/c", cr: "Nirmal Distributors" },
  { ch: "gst", q: "Singh Agencies se udhaar maal kharida — usi bill ka Input SGST wala hissa (₹15,000 par 9%).", dr: "Input SGST A/c", cr: "Singh Agencies" },
  { ch: "gst", q: "Kumar Sons se udhaar maal kharida — usi bill ka Input SGST wala hissa (₹10,000 par 9%).", dr: "Input SGST A/c", cr: "Kumar Sons" },
  { ch: "gst", q: "Nirmal Distributors se udhaar maal kharida — usi bill ka Input SGST wala hissa (₹50,000 par 9%).", dr: "Input SGST A/c", cr: "Nirmal Distributors" },
  { ch: "gst", q: "Yadav Enterprises se udhaar maal kharida — usi bill ka Input SGST wala hissa (₹45,000 par 9%).", dr: "Input SGST A/c", cr: "Yadav Enterprises" },
  { ch: "gst", q: "Ram Traders se udhaar maal kharida — usi bill ka Input SGST wala hissa (₹20,000 par 9%).", dr: "Input SGST A/c", cr: "Ram Traders" },
  { ch: "gst", q: "Suresh ko udhaar maal becha — usi bill ka Output CGST wala hissa (₹60,000 par 9%).", dr: "Suresh", cr: "Output CGST A/c" },
  { ch: "gst", q: "Anita Devi ko udhaar maal becha — usi bill ka Output CGST wala hissa (₹75,000 par 9%).", dr: "Anita Devi", cr: "Output CGST A/c" },
  { ch: "gst", q: "Verma Stores ko udhaar maal becha — usi bill ka Output CGST wala hissa (₹25,000 par 9%).", dr: "Verma Stores", cr: "Output CGST A/c" },
  { ch: "gst", q: "Rajesh Kumar ko udhaar maal becha — usi bill ka Output CGST wala hissa (₹80,000 par 9%).", dr: "Rajesh Kumar", cr: "Output CGST A/c" },
  { ch: "gst", q: "Sharma Brothers ko udhaar maal becha — usi bill ka Output CGST wala hissa (₹35,000 par 9%).", dr: "Sharma Brothers", cr: "Output CGST A/c" },
  { ch: "gst", q: "Rajesh Kumar ko udhaar maal becha — usi bill ka Output SGST wala hissa (₹30,000 par 9%).", dr: "Rajesh Kumar", cr: "Output SGST A/c" },
  { ch: "gst", q: "Sharma Brothers ko udhaar maal becha — usi bill ka Output SGST wala hissa (₹1,00,000 par 9%).", dr: "Sharma Brothers", cr: "Output SGST A/c" },
  { ch: "gst", q: "Priya Enterprises ko udhaar maal becha — usi bill ka Output SGST wala hissa (₹55,000 par 9%).", dr: "Priya Enterprises", cr: "Output SGST A/c" },
  { ch: "gst", q: "Mohan Lal ko udhaar maal becha — usi bill ka Output SGST wala hissa (₹40,000 par 9%).", dr: "Mohan Lal", cr: "Output SGST A/c" },
  { ch: "gst", q: "Bharti Traders ko udhaar maal becha — usi bill ka Output SGST wala hissa (₹15,000 par 9%).", dr: "Bharti Traders", cr: "Output SGST A/c" },
  { ch: "gst", q: "GST ka paisa sarkar ko bank se jama kiya — Output CGST wala hissa (₹11,000).", dr: "Output CGST A/c", cr: "Bank A/c" },
  { ch: "gst", q: "GST ka paisa sarkar ko bank se jama kiya — Output SGST wala hissa (₹18,000).", dr: "Output SGST A/c", cr: "Bank A/c" },
  { ch: "gst", q: "IGST ka ₹30,000 sarkar ko bank se jama kiya.", dr: "Output IGST A/c", cr: "Bank A/c" },
  { ch: "gst", q: "Cheque se ₹1,800 ka maal kharida — usi bill ka Input CGST wala hissa.", dr: "Input CGST A/c", cr: "Bank A/c" },
  { ch: "gst", q: "Cheque se ₹3,500 ka maal kharida — usi bill ka Input SGST wala hissa.", dr: "Input SGST A/c", cr: "Bank A/c" },
  { ch: "gst", q: "GST ka paisa sarkar ko bank se jama kiya — Output CGST wala hissa (₹10,000).", dr: "Output CGST A/c", cr: "Bank A/c" },
  { ch: "gst", q: "GST ka paisa sarkar ko bank se jama kiya — Output SGST wala hissa (₹16,000).", dr: "Output SGST A/c", cr: "Bank A/c" },
  { ch: "gst", q: "IGST ka ₹28,000 sarkar ko bank se jama kiya.", dr: "Output IGST A/c", cr: "Bank A/c" },
  { ch: "gst", q: "Cheque se ₹7,000 ka maal kharida — usi bill ka Input CGST wala hissa.", dr: "Input CGST A/c", cr: "Bank A/c" },
  { ch: "gst", q: "Cheque se ₹2,200 ka maal kharida — usi bill ka Input SGST wala hissa.", dr: "Input SGST A/c", cr: "Bank A/c" },

  /* ---------------- Kharche aur Aamdani (70) ---------------- */
  { ch: "exp", q: "Daak aur courier par ₹600 cash kharch hua.", dr: "Postage A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Business ke kaam se safar par ₹4,500 cash kharch hua.", dr: "Travelling A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Gaadi me petrol ka ₹1,000 cash bhara.", dr: "Petrol A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Maal ki packing par ₹2,000 cash kharch hua.", dr: "Packing A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Vakil ki fees ₹8,000 cash di.", dr: "Legal Fees A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Audit fees ₹2,800 cash di.", dr: "Audit Fees A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Office ka chhota-mota kharcha ₹350 cash hua.", dr: "Office Expenses A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Staff ki chai-nashta par ₹700 cash kharch hua.", dr: "Staff Welfare A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Ek sanstha ko ₹5,500 cash daan diya.", dr: "Donation A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Maal ki dhulai (freight) ₹1,500 cash di.", dr: "Freight A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Saal ka bima premium ₹3,200 cash bhara.", dr: "Insurance A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Agent ko ₹6,500 commission cash diya.", dr: "Commission A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Mobile aur internet ka ₹1,100 ka bill cash me diya.", dr: "Telephone A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Dukaan ke shutter ki marammat par ₹2,000 cash lagaya.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Vigyapan ke pamphlet chhapwane par ₹4,000 cash kharch hua.", dr: "Advertisement A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Bill book aur register par ₹150 cash kharch hua.", dr: "Printing & Stationery A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Helper ko ek din ki mazdoori ₹400 cash di.", dr: "Wages A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Gaadi ki servicing par ₹7,500 cash lagaya.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Bank ka demand draft banwane par ₹750 ka charge cash me diya.", dr: "Bank Charges A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Exhibition me stall lagane ka ₹9,000 cash diya.", dr: "Advertisement A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Staff ke liye ₹2,500 ki vardi cash me kharidi.", dr: "Staff Welfare A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Agreement ki registry par vakil ko ₹5,000 cash diya.", dr: "Legal Fees A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Daak aur courier par ₹1,200 cash kharch hua.", dr: "Postage A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Business ke kaam se safar par ₹1,200 cash kharch hua.", dr: "Travelling A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Gaadi me petrol ka ₹200 cash bhara.", dr: "Petrol A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Maal ki packing par ₹450 cash kharch hua.", dr: "Packing A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Vakil ki fees ₹3,000 cash di.", dr: "Legal Fees A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Audit fees ₹6,000 cash di.", dr: "Audit Fees A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Office ka chhota-mota kharcha ₹800 cash hua.", dr: "Office Expenses A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Staff ki chai-nashta par ₹1,500 cash kharch hua.", dr: "Staff Welfare A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Ek sanstha ko ₹1,800 cash daan diya.", dr: "Donation A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Maal ki dhulai (freight) ₹3,500 cash di.", dr: "Freight A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Saal ka bima premium ₹7,000 cash bhara.", dr: "Insurance A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Agent ko ₹2,200 commission cash diya.", dr: "Commission A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Mobile aur internet ka ₹250 ka bill cash me diya.", dr: "Telephone A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Dukaan ke shutter ki marammat par ₹4,500 cash lagaya.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Vigyapan ke pamphlet chhapwane par ₹8,000 cash kharch hua.", dr: "Advertisement A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Bill book aur register par ₹500 cash kharch hua.", dr: "Printing & Stationery A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Helper ko ek din ki mazdoori ₹900 cash di.", dr: "Wages A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Gaadi ki servicing par ₹2,800 cash lagaya.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Bank ka demand draft banwane par ₹1,800 ka charge cash me diya.", dr: "Bank Charges A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Exhibition me stall lagane ka ₹15,000 cash diya.", dr: "Advertisement A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Staff ke liye ₹5,500 ki vardi cash me kharidi.", dr: "Staff Welfare A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Agreement ki registry par vakil ko ₹1,500 cash diya.", dr: "Legal Fees A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Daak aur courier par ₹300 cash kharch hua.", dr: "Postage A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Business ke kaam se safar par ₹3,200 cash kharch hua.", dr: "Travelling A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Gaadi me petrol ka ₹600 cash bhara.", dr: "Petrol A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Maal ki packing par ₹1,000 cash kharch hua.", dr: "Packing A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Dukaan ka ek kamra kiraye par diya, ₹25,000 cash mila.", dr: "Cash A/c", cr: "Rent Received A/c" },
  { ch: "exp", q: "Dalali (commission) ₹6,500 cash mili.", dr: "Cash A/c", cr: "Commission Received A/c" },
  { ch: "exp", q: "Jama paise par ₹2,000 byaaj cash mila.", dr: "Cash A/c", cr: "Interest Received A/c" },
  { ch: "exp", q: "Godown kiraye par diya, ₹8,500 seedha bank khaate me aaya.", dr: "Bank A/c", cr: "Rent Received A/c" },
  { ch: "exp", q: "Commission ka ₹4,000 bank khaate me aaya.", dr: "Bank A/c", cr: "Commission Received A/c" },
  { ch: "exp", q: "Dukaan ka ek kamra kiraye par diya, ₹14,000 cash mila.", dr: "Cash A/c", cr: "Rent Received A/c" },
  { ch: "exp", q: "Dalali (commission) ₹7,500 cash mili.", dr: "Cash A/c", cr: "Commission Received A/c" },
  { ch: "exp", q: "Jama paise par ₹2,500 byaaj cash mila.", dr: "Cash A/c", cr: "Interest Received A/c" },
  { ch: "exp", q: "Godown kiraye par diya, ₹24,000 seedha bank khaate me aaya.", dr: "Bank A/c", cr: "Rent Received A/c" },
  { ch: "exp", q: "Commission ka ₹5,000 bank khaate me aaya.", dr: "Bank A/c", cr: "Commission Received A/c" },
  { ch: "exp", q: "Dukaan ka ek kamra kiraye par diya, ₹7,500 cash mila.", dr: "Cash A/c", cr: "Rent Received A/c" },
  { ch: "exp", q: "Dalali (commission) ₹1,200 cash mili.", dr: "Cash A/c", cr: "Commission Received A/c" },
  { ch: "exp", q: "Jama paise par ₹3,000 byaaj cash mila.", dr: "Cash A/c", cr: "Interest Received A/c" },
  { ch: "exp", q: "Godown kiraye par diya, ₹12,500 seedha bank khaate me aaya.", dr: "Bank A/c", cr: "Rent Received A/c" },
  { ch: "exp", q: "Ram Traders ka maal laane ka bhada (carriage) ₹2,000 cash diya.", dr: "Carriage A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Gupta & Co. ka maal laane ka bhada (carriage) ₹350 cash diya.", dr: "Carriage A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Singh Agencies ka maal laane ka bhada (carriage) ₹700 cash diya.", dr: "Carriage A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Kumar Sons ka maal laane ka bhada (carriage) ₹1,100 cash diya.", dr: "Carriage A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Nirmal Distributors ka maal laane ka bhada (carriage) ₹150 cash diya.", dr: "Carriage A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Yadav Enterprises ka maal laane ka bhada (carriage) ₹400 cash diya.", dr: "Carriage A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Ram Traders ka maal laane ka bhada (carriage) ₹750 cash diya.", dr: "Carriage A/c", cr: "Cash A/c" },
  { ch: "exp", q: "Gupta & Co. ka maal laane ka bhada (carriage) ₹1,200 cash diya.", dr: "Carriage A/c", cr: "Cash A/c" },

  /* ---------------- Asset kharidna, bechna, Depreciation (56) ---------------- */
  { ch: "asset", q: "Business ke liye ₹40,000 ka furniture cheque se kharida.", dr: "Furniture A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹1,75,000 ki machine cheque se kharidi.", dr: "Machinery A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹65,000 ka computer cheque se kharida.", dr: "Computer A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹3,50,000 ki gaadi cheque se kharidi.", dr: "Vehicle A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹7,50,000 ki building cheque se kharidi.", dr: "Building A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹2,50,000 ki zameen cheque se kharidi.", dr: "Land A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹1,00,000 ka generator cheque se kharida.", dr: "Generator A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹30,000 ka AC cheque se kharida.", dr: "Air Conditioner A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹22,000 ke auzaar cheque se kharide.", dr: "Tools A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹55,000 ka furniture cheque se kharida.", dr: "Furniture A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹5,00,000 ki machine cheque se kharidi.", dr: "Machinery A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹80,000 ka computer cheque se kharida.", dr: "Computer A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹2,00,000 ki gaadi cheque se kharidi.", dr: "Vehicle A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹4,00,000 ki building cheque se kharidi.", dr: "Building A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹1,50,000 ki zameen cheque se kharidi.", dr: "Land A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹1,25,000 ka generator cheque se kharida.", dr: "Generator A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹45,000 ka AC cheque se kharida.", dr: "Air Conditioner A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Business ke liye ₹6,000 ke auzaar cheque se kharide.", dr: "Tools A/c", cr: "Bank A/c" },
  { ch: "asset", q: "Purana computer ₹70,000 me cash bech diya (usi daam par).", dr: "Cash A/c", cr: "Computer A/c" },
  { ch: "asset", q: "Purani gaadi ₹3,00,000 me cash bech di (usi daam par).", dr: "Cash A/c", cr: "Vehicle A/c" },
  { ch: "asset", q: "Purani building ₹6,00,000 me cash bech di (usi daam par).", dr: "Cash A/c", cr: "Building A/c" },
  { ch: "asset", q: "Purani zameen ₹2,25,000 me cash bech di (usi daam par).", dr: "Cash A/c", cr: "Land A/c" },
  { ch: "asset", q: "Purana generator ₹1,10,000 me cash bech diya (usi daam par).", dr: "Cash A/c", cr: "Generator A/c" },
  { ch: "asset", q: "Purana AC ₹35,000 me cash bech diya (usi daam par).", dr: "Cash A/c", cr: "Air Conditioner A/c" },
  { ch: "asset", q: "Purane auzaar ₹12,000 me cash bech diye (usi daam par).", dr: "Cash A/c", cr: "Tools A/c" },
  { ch: "asset", q: "Purana furniture ₹60,000 me cash bech diya (usi daam par).", dr: "Cash A/c", cr: "Furniture A/c" },
  { ch: "asset", q: "Purani machine ₹4,50,000 me cash bech di (usi daam par).", dr: "Cash A/c", cr: "Machinery A/c" },
  { ch: "asset", q: "Purana computer ₹90,000 me cash bech diya (usi daam par).", dr: "Cash A/c", cr: "Computer A/c" },
  { ch: "asset", q: "Purani gaadi ₹1,75,000 me cash bech di (usi daam par).", dr: "Cash A/c", cr: "Vehicle A/c" },
  { ch: "asset", q: "Purani building ₹3,50,000 me cash bech di (usi daam par).", dr: "Cash A/c", cr: "Building A/c" },
  { ch: "asset", q: "Saal ke aakhir me machine par ₹20,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Machinery A/c" },
  { ch: "asset", q: "Saal ke aakhir me computer par ₹32,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Computer A/c" },
  { ch: "asset", q: "Saal ke aakhir me gaadi par ₹11,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Vehicle A/c" },
  { ch: "asset", q: "Saal ke aakhir me building par ₹18,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Building A/c" },
  { ch: "asset", q: "Saal ke aakhir me generator par ₹30,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Generator A/c" },
  { ch: "asset", q: "Saal ke aakhir me AC par ₹10,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Air Conditioner A/c" },
  { ch: "asset", q: "Saal ke aakhir me auzaar par ₹16,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Tools A/c" },
  { ch: "asset", q: "Saal ke aakhir me furniture par ₹28,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Furniture A/c" },
  { ch: "asset", q: "Saal ke aakhir me machine par ₹9,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Machinery A/c" },
  { ch: "asset", q: "Saal ke aakhir me computer par ₹15,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Computer A/c" },
  { ch: "asset", q: "Saal ke aakhir me gaadi par ₹25,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Vehicle A/c" },
  { ch: "asset", q: "Saal ke aakhir me building par ₹8,500 depreciation lagaya.", dr: "Depreciation A/c", cr: "Building A/c" },
  { ch: "asset", q: "Saal ke aakhir me generator par ₹14,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Generator A/c" },
  { ch: "asset", q: "Saal ke aakhir me AC par ₹24,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Air Conditioner A/c" },
  { ch: "asset", q: "Saal ke aakhir me auzaar par ₹7,500 depreciation lagaya.", dr: "Depreciation A/c", cr: "Tools A/c" },
  { ch: "asset", q: "Saal ke aakhir me furniture par ₹12,500 depreciation lagaya.", dr: "Depreciation A/c", cr: "Furniture A/c" },
  { ch: "asset", q: "Saal ke aakhir me machine par ₹22,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Machinery A/c" },
  { ch: "asset", q: "Saal ke aakhir me computer par ₹6,000 depreciation lagaya.", dr: "Depreciation A/c", cr: "Computer A/c" },
  { ch: "asset", q: "Gaadi ki marammat par ₹6,000 cash kharch hua.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "asset", q: "Building ki marammat par ₹1,800 cash kharch hua.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "asset", q: "Generator ki marammat par ₹3,500 cash kharch hua.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "asset", q: "AC ki marammat par ₹7,000 cash kharch hua.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "asset", q: "Auzaar ki marammat par ₹2,200 cash kharch hua.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "asset", q: "Furniture ki marammat par ₹4,500 cash kharch hua.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "asset", q: "Machine ki marammat par ₹8,000 cash kharch hua.", dr: "Repairs A/c", cr: "Cash A/c" },
  { ch: "asset", q: "Computer ki marammat par ₹2,800 cash kharch hua.", dr: "Repairs A/c", cr: "Cash A/c" },

  /* ---------------- Adjustment — Outstanding, Prepaid, Bad Debts (56) ---------------- */
  { ch: "adjust", q: "Is mahine ki salary ₹12,000 abhi tak di nahi gayi — dena baaki hai.", dr: "Salary A/c", cr: "Outstanding Salary A/c" },
  { ch: "adjust", q: "Is mahine ka kiraya ₹20,000 abhi tak diya nahi gaya — dena baaki hai.", dr: "Rent A/c", cr: "Outstanding Rent A/c" },
  { ch: "adjust", q: "Is mahine ki mazdoori ₹5,500 abhi tak di nahi gayi — dena baaki hai.", dr: "Wages A/c", cr: "Outstanding Wages A/c" },
  { ch: "adjust", q: "Is mahine ka bijli ka bill ₹1,500 abhi tak diya nahi gaya — dena baaki hai.", dr: "Electricity A/c", cr: "Outstanding Electricity A/c" },
  { ch: "adjust", q: "Is mahine ki salary ₹32,000 abhi tak di nahi gayi — dena baaki hai.", dr: "Salary A/c", cr: "Outstanding Salary A/c" },
  { ch: "adjust", q: "Is mahine ka kiraya ₹11,000 abhi tak diya nahi gaya — dena baaki hai.", dr: "Rent A/c", cr: "Outstanding Rent A/c" },
  { ch: "adjust", q: "Is mahine ki mazdoori ₹3,200 abhi tak di nahi gayi — dena baaki hai.", dr: "Wages A/c", cr: "Outstanding Wages A/c" },
  { ch: "adjust", q: "Is mahine ka bijli ka bill ₹6,500 abhi tak diya nahi gaya — dena baaki hai.", dr: "Electricity A/c", cr: "Outstanding Electricity A/c" },
  { ch: "adjust", q: "Is mahine ki salary ₹18,000 abhi tak di nahi gayi — dena baaki hai.", dr: "Salary A/c", cr: "Outstanding Salary A/c" },
  { ch: "adjust", q: "Is mahine ka kiraya ₹30,000 abhi tak diya nahi gaya — dena baaki hai.", dr: "Rent A/c", cr: "Outstanding Rent A/c" },
  { ch: "adjust", q: "Is mahine ki mazdoori ₹2,000 abhi tak di nahi gayi — dena baaki hai.", dr: "Wages A/c", cr: "Outstanding Wages A/c" },
  { ch: "adjust", q: "Is mahine ka bijli ka bill ₹4,000 abhi tak diya nahi gaya — dena baaki hai.", dr: "Electricity A/c", cr: "Outstanding Electricity A/c" },
  { ch: "adjust", q: "Pichhle mahine ka bakaya kiraya ₹10,000 ab cash de diya.", dr: "Outstanding Rent A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ki bakaya mazdoori ₹7,500 ab cash de di.", dr: "Outstanding Wages A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ka bakaya bijli ka bill ₹2,500 ab cash de diya.", dr: "Outstanding Electricity A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ki bakaya salary ₹16,000 ab cash de di.", dr: "Outstanding Salary A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ka bakaya kiraya ₹28,000 ab cash de diya.", dr: "Outstanding Rent A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ki bakaya mazdoori ₹5,000 ab cash de di.", dr: "Outstanding Wages A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ka bakaya bijli ka bill ₹1,200 ab cash de diya.", dr: "Outstanding Electricity A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ki bakaya salary ₹9,000 ab cash de di.", dr: "Outstanding Salary A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ka bakaya kiraya ₹15,000 ab cash de diya.", dr: "Outstanding Rent A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ki bakaya mazdoori ₹3,000 ab cash de di.", dr: "Outstanding Wages A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ka bakaya bijli ka bill ₹6,000 ab cash de diya.", dr: "Outstanding Electricity A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Pichhle mahine ki bakaya salary ₹25,000 ab cash de di.", dr: "Outstanding Salary A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Agle saal ka insurance ₹1,800 abhi cash me de diya.", dr: "Prepaid Insurance A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Agle teen mahine ka kiraya ₹8,500 pehle hi cash de diya.", dr: "Prepaid Rent A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Agle saal ka bima premium ₹3,500 cheque se pehle hi de diya.", dr: "Prepaid Insurance A/c", cr: "Bank A/c" },
  { ch: "adjust", q: "Godown ka agle saal ka kiraya ₹25,000 cash me pehle hi chuka diya.", dr: "Prepaid Rent A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Agle saal ka insurance ₹7,000 abhi cash me de diya.", dr: "Prepaid Insurance A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Agle teen mahine ka kiraya ₹14,000 pehle hi cash de diya.", dr: "Prepaid Rent A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Agle saal ka bima premium ₹2,200 cheque se pehle hi de diya.", dr: "Prepaid Insurance A/c", cr: "Bank A/c" },
  { ch: "adjust", q: "Godown ka agle saal ka kiraya ₹50,000 cash me pehle hi chuka diya.", dr: "Prepaid Rent A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Agle saal ka insurance ₹4,500 abhi cash me de diya.", dr: "Prepaid Insurance A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Agle teen mahine ka kiraya ₹24,000 pehle hi cash de diya.", dr: "Prepaid Rent A/c", cr: "Cash A/c" },
  { ch: "adjust", q: "Suresh ka ₹8,000 doob gaya — ab wasool nahi hoga.", dr: "Bad Debts A/c", cr: "Suresh" },
  { ch: "adjust", q: "Anita Devi ka ₹2,800 doob gaya — ab wasool nahi hoga.", dr: "Bad Debts A/c", cr: "Anita Devi" },
  { ch: "adjust", q: "Verma Stores ka ₹5,500 doob gaya — ab wasool nahi hoga.", dr: "Bad Debts A/c", cr: "Verma Stores" },
  { ch: "adjust", q: "Rajesh Kumar ka ₹1,500 doob gaya — ab wasool nahi hoga.", dr: "Bad Debts A/c", cr: "Rajesh Kumar" },
  { ch: "adjust", q: "Sharma Brothers ka ₹3,200 doob gaya — ab wasool nahi hoga.", dr: "Bad Debts A/c", cr: "Sharma Brothers" },
  { ch: "adjust", q: "Priya Enterprises ka ₹6,500 doob gaya — ab wasool nahi hoga.", dr: "Bad Debts A/c", cr: "Priya Enterprises" },
  { ch: "adjust", q: "Mohan Lal ka ₹2,000 doob gaya — ab wasool nahi hoga.", dr: "Bad Debts A/c", cr: "Mohan Lal" },
  { ch: "adjust", q: "Bharti Traders ka ₹4,000 doob gaya — ab wasool nahi hoga.", dr: "Bad Debts A/c", cr: "Bharti Traders" },
  { ch: "adjust", q: "Suresh ka ₹7,500 doob gaya — ab wasool nahi hoga.", dr: "Bad Debts A/c", cr: "Suresh" },
  { ch: "adjust", q: "Anita Devi ka ₹2,500 doob gaya — ab wasool nahi hoga.", dr: "Bad Debts A/c", cr: "Anita Devi" },
  { ch: "adjust", q: "Kamaya hua ₹5,000 commission abhi mila nahi hai — lena baaki hai.", dr: "Accrued Commission A/c", cr: "Commission Received A/c" },
  { ch: "adjust", q: "Kamaya hua ₹1,200 commission abhi mila nahi hai — lena baaki hai.", dr: "Accrued Commission A/c", cr: "Commission Received A/c" },
  { ch: "adjust", q: "Kamaya hua ₹3,000 commission abhi mila nahi hai — lena baaki hai.", dr: "Accrued Commission A/c", cr: "Commission Received A/c" },
  { ch: "adjust", q: "Kamaya hua ₹6,000 commission abhi mila nahi hai — lena baaki hai.", dr: "Accrued Commission A/c", cr: "Commission Received A/c" },
  { ch: "adjust", q: "Kamaya hua ₹1,800 commission abhi mila nahi hai — lena baaki hai.", dr: "Accrued Commission A/c", cr: "Commission Received A/c" },
  { ch: "adjust", q: "Kamaya hua ₹3,500 commission abhi mila nahi hai — lena baaki hai.", dr: "Accrued Commission A/c", cr: "Commission Received A/c" },
  { ch: "adjust", q: "Bakaya commission ₹7,000 ab cash me mil gaya.", dr: "Cash A/c", cr: "Accrued Commission A/c" },
  { ch: "adjust", q: "Bakaya commission ₹2,200 ab cash me mil gaya.", dr: "Cash A/c", cr: "Accrued Commission A/c" },
  { ch: "adjust", q: "Bakaya commission ₹4,500 ab cash me mil gaya.", dr: "Cash A/c", cr: "Accrued Commission A/c" },
  { ch: "adjust", q: "Bakaya commission ₹8,000 ab cash me mil gaya.", dr: "Cash A/c", cr: "Accrued Commission A/c" },
  { ch: "adjust", q: "Bakaya commission ₹2,800 ab cash me mil gaya.", dr: "Cash A/c", cr: "Accrued Commission A/c" },
  { ch: "adjust", q: "Bakaya commission ₹5,500 ab cash me mil gaya.", dr: "Cash A/c", cr: "Accrued Commission A/c" },

  /* ---------------- Return, Discount aur Drawings (58) ---------------- */
  { ch: "retdis", q: "Ram Traders ko ₹7,500 ka kharab maal wapas kiya.", dr: "Ram Traders", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Gupta & Co. ko ₹12,500 ka kharab maal wapas kiya.", dr: "Gupta & Co.", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Singh Agencies ko ₹22,000 ka kharab maal wapas kiya.", dr: "Singh Agencies", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Kumar Sons ko ₹6,000 ka kharab maal wapas kiya.", dr: "Kumar Sons", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Nirmal Distributors ko ₹12,000 ka kharab maal wapas kiya.", dr: "Nirmal Distributors", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Yadav Enterprises ko ₹20,000 ka kharab maal wapas kiya.", dr: "Yadav Enterprises", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Ram Traders ko ₹32,000 ka kharab maal wapas kiya.", dr: "Ram Traders", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Gupta & Co. ko ₹11,000 ka kharab maal wapas kiya.", dr: "Gupta & Co.", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Singh Agencies ko ₹18,000 ka kharab maal wapas kiya.", dr: "Singh Agencies", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Kumar Sons ko ₹30,000 ka kharab maal wapas kiya.", dr: "Kumar Sons", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Nirmal Distributors ko ₹10,000 ka kharab maal wapas kiya.", dr: "Nirmal Distributors", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Yadav Enterprises ko ₹16,000 ka kharab maal wapas kiya.", dr: "Yadav Enterprises", cr: "Purchase Return A/c" },
  { ch: "retdis", q: "Suresh ne ₹1,500 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Suresh" },
  { ch: "retdis", q: "Anita Devi ne ₹3,200 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Anita Devi" },
  { ch: "retdis", q: "Verma Stores ne ₹6,500 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Verma Stores" },
  { ch: "retdis", q: "Rajesh Kumar ne ₹2,000 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Rajesh Kumar" },
  { ch: "retdis", q: "Sharma Brothers ne ₹4,000 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Sharma Brothers" },
  { ch: "retdis", q: "Priya Enterprises ne ₹7,500 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Priya Enterprises" },
  { ch: "retdis", q: "Mohan Lal ne ₹2,500 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Mohan Lal" },
  { ch: "retdis", q: "Bharti Traders ne ₹5,000 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Bharti Traders" },
  { ch: "retdis", q: "Suresh ne ₹1,200 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Suresh" },
  { ch: "retdis", q: "Anita Devi ne ₹3,000 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Anita Devi" },
  { ch: "retdis", q: "Verma Stores ne ₹6,000 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Verma Stores" },
  { ch: "retdis", q: "Rajesh Kumar ne ₹1,800 ka maal wapas kiya.", dr: "Sales Return A/c", cr: "Rajesh Kumar" },
  { ch: "retdis", q: "Anita Devi ko jaldi paisa dene par ₹200 ka discount diya.", dr: "Discount Allowed A/c", cr: "Anita Devi" },
  { ch: "retdis", q: "Verma Stores ko jaldi paisa dene par ₹450 ka discount diya.", dr: "Discount Allowed A/c", cr: "Verma Stores" },
  { ch: "retdis", q: "Rajesh Kumar ko jaldi paisa dene par ₹800 ka discount diya.", dr: "Discount Allowed A/c", cr: "Rajesh Kumar" },
  { ch: "retdis", q: "Sharma Brothers ko jaldi paisa dene par ₹1,500 ka discount diya.", dr: "Discount Allowed A/c", cr: "Sharma Brothers" },
  { ch: "retdis", q: "Priya Enterprises ko jaldi paisa dene par ₹250 ka discount diya.", dr: "Discount Allowed A/c", cr: "Priya Enterprises" },
  { ch: "retdis", q: "Mohan Lal ko jaldi paisa dene par ₹500 ka discount diya.", dr: "Discount Allowed A/c", cr: "Mohan Lal" },
  { ch: "retdis", q: "Bharti Traders ko jaldi paisa dene par ₹900 ka discount diya.", dr: "Discount Allowed A/c", cr: "Bharti Traders" },
  { ch: "retdis", q: "Suresh ko jaldi paisa dene par ₹1,800 ka discount diya.", dr: "Discount Allowed A/c", cr: "Suresh" },
  { ch: "retdis", q: "Anita Devi ko jaldi paisa dene par ₹300 ka discount diya.", dr: "Discount Allowed A/c", cr: "Anita Devi" },
  { ch: "retdis", q: "Verma Stores ko jaldi paisa dene par ₹600 ka discount diya.", dr: "Discount Allowed A/c", cr: "Verma Stores" },
  { ch: "retdis", q: "Gupta & Co. ne bill jaldi chukane par ₹1,000 ka discount diya.", dr: "Gupta & Co.", cr: "Discount Received A/c" },
  { ch: "retdis", q: "Singh Agencies ne bill jaldi chukane par ₹2,000 ka discount diya.", dr: "Singh Agencies", cr: "Discount Received A/c" },
  { ch: "retdis", q: "Kumar Sons ne bill jaldi chukane par ₹350 ka discount diya.", dr: "Kumar Sons", cr: "Discount Received A/c" },
  { ch: "retdis", q: "Nirmal Distributors ne bill jaldi chukane par ₹700 ka discount diya.", dr: "Nirmal Distributors", cr: "Discount Received A/c" },
  { ch: "retdis", q: "Yadav Enterprises ne bill jaldi chukane par ₹1,100 ka discount diya.", dr: "Yadav Enterprises", cr: "Discount Received A/c" },
  { ch: "retdis", q: "Ram Traders ne bill jaldi chukane par ₹150 ka discount diya.", dr: "Ram Traders", cr: "Discount Received A/c" },
  { ch: "retdis", q: "Gupta & Co. ne bill jaldi chukane par ₹400 ka discount diya.", dr: "Gupta & Co.", cr: "Discount Received A/c" },
  { ch: "retdis", q: "Singh Agencies ne bill jaldi chukane par ₹750 ka discount diya.", dr: "Singh Agencies", cr: "Discount Received A/c" },
  { ch: "retdis", q: "Kumar Sons ne bill jaldi chukane par ₹1,200 ka discount diya.", dr: "Kumar Sons", cr: "Discount Received A/c" },
  { ch: "retdis", q: "Nirmal Distributors ne bill jaldi chukane par ₹200 ka discount diya.", dr: "Nirmal Distributors", cr: "Discount Received A/c" },
  { ch: "retdis", q: "Maalik ne apne ghar ke liye dukaan se ₹3,500 cash nikala.", dr: "Drawings A/c", cr: "Cash A/c" },
  { ch: "retdis", q: "Maalik ne apne liye dukaan se ₹7,000 ka maal nikala.", dr: "Drawings A/c", cr: "Purchases A/c" },
  { ch: "retdis", q: "Maalik ne business ke bank khaate se apne liye ₹28,000 nikale.", dr: "Drawings A/c", cr: "Bank A/c" },
  { ch: "retdis", q: "Maalik ka ghar ka bijli bill ₹450 business ke cash se bhara.", dr: "Drawings A/c", cr: "Cash A/c" },
  { ch: "retdis", q: "Maalik ne apne bete ki fees ₹9,000 business ke bank khaate se bhari.", dr: "Drawings A/c", cr: "Bank A/c" },
  { ch: "retdis", q: "Maalik ne apne ghar ke liye dukaan se ₹2,200 cash nikala.", dr: "Drawings A/c", cr: "Cash A/c" },
  { ch: "retdis", q: "Maalik ne apne liye dukaan se ₹4,500 ka maal nikala.", dr: "Drawings A/c", cr: "Purchases A/c" },
  { ch: "retdis", q: "Maalik ne business ke bank khaate se apne liye ₹15,000 nikale.", dr: "Drawings A/c", cr: "Bank A/c" },
  { ch: "retdis", q: "Maalik ka ghar ka bijli bill ₹800 business ke cash se bhara.", dr: "Drawings A/c", cr: "Cash A/c" },
  { ch: "retdis", q: "Maalik ne apne bete ki fees ₹25,000 business ke bank khaate se bhari.", dr: "Drawings A/c", cr: "Bank A/c" },
  { ch: "retdis", q: "Maalik ne apne ghar ke liye dukaan se ₹8,000 cash nikala.", dr: "Drawings A/c", cr: "Cash A/c" },
  { ch: "retdis", q: "Maalik ne apne liye dukaan se ₹2,800 ka maal nikala.", dr: "Drawings A/c", cr: "Purchases A/c" },
  { ch: "retdis", q: "Maalik ne business ke bank khaate se apne liye ₹8,500 nikale.", dr: "Drawings A/c", cr: "Bank A/c" },
  { ch: "retdis", q: "Maalik ka ghar ka bijli bill ₹1,500 business ke cash se bhara.", dr: "Drawings A/c", cr: "Cash A/c" }
]);
